namespace GA.Business.DSL.Generators

open System
open System.Collections.Generic
open GA.Domain.Core.Theory.Atonal

/// <summary>
/// Represents the elements of the 48-order transformation group acting on pitch-class sets.
/// Generated by Transposition (0..11), Inversion (bool), and Complementation (bool).
/// </summary>
type OptickTransformation =
    { Transposition: int // 0..11
      Inversion: bool
      Complement: bool }

    /// Identity transformation: no transposition, no inversion, no complementation
    static member Identity = { Transposition = 0; Inversion = false; Complement = false }

    /// Compose two transformations: self is applied first, then other.
    /// other ∘ self
    member self.Compose(other: OptickTransformation) : OptickTransformation =
        let inv' = self.Inversion <> other.Inversion
        // If other has inversion, it flips the transposition of self.
        let tSelfFlipped = if other.Inversion then (12 - self.Transposition) % 12 else self.Transposition
        let t' = (tSelfFlipped + other.Transposition) % 12
        let comp' = self.Complement <> other.Complement
        { Transposition = t'; Inversion = inv'; Complement = comp' }

    /// Inverse transformation
    member self.Inverse() : OptickTransformation =
        let tInv = if self.Inversion then self.Transposition else (12 - self.Transposition) % 12
        { Transposition = tInv; Inversion = self.Inversion; Complement = self.Complement }

    /// Apply the transformation to an array of pitch classes (0..11)
    member self.Apply(pcs: int[]) : int[] =
        let inverted =
            if self.Inversion then
                pcs |> Array.map (fun x -> (12 - x) % 12)
            else
                pcs
        let transposed =
            inverted |> Array.map (fun x -> (x + self.Transposition) % 12)
        let sorted = transposed |> Array.distinct |> Array.sort
        if self.Complement then
            let all = [| 0..11 |]
            all |> Array.filter (fun x -> not (Array.contains x sorted))
        else
            sorted

    /// Apply the transformation to a PitchClassSet
    member self.Apply(pcs: PitchClassSet) : PitchClassSet =
        let rawPcs = pcs |> Seq.map (fun pc -> pc.Value) |> Seq.toArray
        let transformedRaw = self.Apply(rawPcs)
        let pcObjects = transformedRaw |> Array.map (fun v -> PitchClass.FromValue(v))
        PitchClassSet(pcObjects :> seq<PitchClass>)

/// <summary>
/// Signed pitch class changes representing elements of the Grothendieck group Z^12.
/// </summary>
type PcDelta =
    { Changes: int[] }
    static member Zero = { Changes = Array.zeroCreate 12 }
    static member Between (source: PitchClassSet) (target: PitchClassSet) : PcDelta =
        let sourceCounts = Array.zeroCreate 12
        for pc in source do sourceCounts.[pc.Value] <- 1
        let targetCounts = Array.zeroCreate 12
        for pc in target do targetCounts.[pc.Value] <- 1
        let diff = Array.init 12 (fun i -> targetCounts.[i] - sourceCounts.[i])
        { Changes = diff }
    static member (+) (a: PcDelta, b: PcDelta) : PcDelta =
        { Changes = Array.init 12 (fun i -> a.Changes.[i] + b.Changes.[i]) }
    static member (~-) (a: PcDelta) : PcDelta =
        { Changes = a.Changes |> Array.map (fun x -> -x) }
    static member (-) (a: PcDelta, b: PcDelta) : PcDelta =
        a + (-b)

/// <summary>
/// Signed interval class vector changes representing elements of the Grothendieck group Z^6.
/// </summary>
type IcvDelta =
    { Changes: int[] }
    static member Zero = { Changes = Array.zeroCreate 6 }
    static member Between (source: IntervalClassVector) (target: IntervalClassVector) : IcvDelta =
        let sArr = source |> Seq.toArray
        let tArr = target |> Seq.toArray
        let diff = Array.init 6 (fun i -> tArr.[i] - sArr.[i])
        { Changes = diff }
    static member (+) (a: IcvDelta, b: IcvDelta) : IcvDelta =
        { Changes = Array.init 6 (fun i -> a.Changes.[i] + b.Changes.[i]) }
    static member (~-) (a: IcvDelta) : IcvDelta =
        { Changes = a.Changes |> Array.map (fun x -> -x) }
    static member (-) (a: IcvDelta, b: IcvDelta) : IcvDelta =
        a + (-b)

/// <summary>
/// Partial actions on PitchClassSets that can fail when preconditions are unmet.
/// </summary>
type MorphismError =
    | InsufficientCardinality of expected: int * actual: int
    | InvalidParallelShift
    | NonComposableDomains of src: string * tgt: string

type PartialTransformation =
    | Drop2Voicing
    | ParallelMinorShift
    | AddTensionInterval of semitones: int

    member self.Apply(pcs: PitchClassSet) : Result<PitchClassSet, MorphismError> =
        match self with
        | Drop2Voicing ->
            if pcs.Count < 4 then
                Error (InsufficientCardinality (4, pcs.Count))
            else
                Ok pcs
        | ParallelMinorShift ->
            let contains pc = pcs |> Seq.exists (fun x -> x.Value = pc)
            if pcs.Count = 7 && contains 4 && contains 9 && contains 11 then
                let newPcs =
                    pcs
                    |> Seq.map (fun pc ->
                        match pc.Value with
                        | 4 -> 3
                        | 9 -> 8
                        | 11 -> 10
                        | x -> x)
                    |> Seq.toArray
                let pcObjects = newPcs |> Array.map (fun v -> PitchClass.FromValue(v))
                Ok (PitchClassSet(pcObjects :> seq<PitchClass>))
            else
                Error InvalidParallelShift
        | AddTensionInterval semitones ->
            if pcs.Count >= 11 then
                Error (InsufficientCardinality (10, pcs.Count))
            else
                let current = pcs |> Seq.map (fun pc -> pc.Value) |> Seq.toList
                let root = if current.Length > 0 then current.[0] else 0
                let newPc = (root + semitones) % 12
                let nextList = (newPc :: current) |> List.distinct |> List.sort |> List.toArray
                let pcObjects = nextList |> Array.map (fun v -> PitchClass.FromValue(v))
                Ok (PitchClassSet(pcObjects :> seq<PitchClass>))

/// <summary>
/// Nodes in the OPTICK hierarchy
/// </summary>
type OptickNode =
    | PitchClassSetNode of PitchClassSet
    | SetClassNode of SetClass
    | OpticKClassNode of OpticKClass

    member self.Representative : PitchClassSet =
        match self with
        | PitchClassSetNode pcs -> pcs
        | SetClassNode sc -> sc.PrimeForm
        | OpticKClassNode okc -> okc.Representative.PrimeForm

/// <summary>
/// A path of sequential transformations in the category.
/// </summary>
type Path =
    { Transformations: OptickTransformation list }

    member self.Evaluate(start: PitchClassSet) : PitchClassSet =
        let mutable current = start
        for t in self.Transformations do
            current <- t.Apply(current)
        current

    member self.Accumulate() : OptickTransformation =
        self.Transformations
        |> List.fold (fun acc t -> acc.Compose(t)) OptickTransformation.Identity

type PathComparisonResult =
    | Equivalent
    | Homologous
    | Incompatible of endA: PitchClassSet * endB: PitchClassSet

module PathReasoning =
    let comparePaths (pathA: Path) (pathB: Path) (start: PitchClassSet) : PathComparisonResult =
        let endA = pathA.Evaluate(start)
        let endB = pathB.Evaluate(start)
        if endA.Id <> endB.Id then
            Incompatible (endA, endB)
        else
            let accA = pathA.Accumulate()
            let accB = pathB.Accumulate()
            if accA = accB then
                Equivalent
            else
                Homologous

type DifferenceRecipe =
    | SameOrbitRecipe of OptickTransformation
    | GeneralAdditiveRecipe of PcDelta * IcvDelta

module ProductQueries =
    let computeDifferenceRecipe (source: PitchClassSet) (target: PitchClassSet) : DifferenceRecipe =
        let sourceSc = source.PrimeForm
        let targetSc = target.PrimeForm
        if sourceSc.Id = targetSc.Id then
            let allTransformations =
                [ for t in 0..11 do
                    for inv in [false; true] do
                        yield { Transposition = t; Inversion = inv; Complement = false } ]
            let matchingOpt =
                allTransformations
                |> List.tryFind (fun t -> (t.Apply(source)).Id = target.Id)
            match matchingOpt with
            | Some t -> SameOrbitRecipe t
            | None ->
                let pcD = PcDelta.Between source target
                let icvD = IcvDelta.Between source.IntervalClassVector target.IntervalClassVector
                GeneralAdditiveRecipe (pcD, icvD)
        else
            let pcD = PcDelta.Between source target
            let icvD = IcvDelta.Between source.IntervalClassVector target.IntervalClassVector
            GeneralAdditiveRecipe (pcD, icvD)

    let generateHardNegatives (start: PitchClassSet) (path: Path) : (PitchClassSet * OptickTransformation * string) list =
        let correctAcc = path.Accumulate()
        let offByOneTrans = { correctAcc with Transposition = (correctAcc.Transposition + 1) % 12 }
        let negTarget1 = offByOneTrans.Apply(start)
        let offInversion = { correctAcc with Inversion = not correctAcc.Inversion }
        let negTarget2 = offInversion.Apply(start)
        [ (negTarget1, offByOneTrans, "Off-by-one semitone transposition")
          (negTarget2, offInversion, "Incorrect inversion application") ]
