namespace GaCLI.Commands;

using GA.Business.Assets.Assets;
using Microsoft.Extensions.Logging;

/// <summary>
///     CLI command for importing 3D assets (GLB files) into the Guitar Alchemist asset library
/// </summary>
public class AssetImportCommand(IAssetLibraryService assetService, ILogger<AssetImportCommand> logger)
{
    private readonly ILogger<AssetImportCommand> _logger = logger;

    /// <summary>
    ///     Import a single GLB file
    /// </summary>
    public async Task<int> ImportGlbAsync(
        string path,
        string? name = null,
        AssetCategory? category = null,
        string? license = null,
        string? source = null,
        string? author = null,
        Dictionary<string, string>? tags = null,
        bool verbose = false)
    {
        try
        {
            if (verbose)
            {
                Console.WriteLine($"Importing GLB file: {path}");
            }

            if (!File.Exists(path))
            {
                Console.WriteLine($"Error: File not found: {path}");
                return 1;
            }

            if (!path.EndsWith(".glb", StringComparison.OrdinalIgnoreCase))
            {
                Console.WriteLine("Error: File must be a .glb file");
                return 1;
            }

            // Build metadata
            var metadata = new AssetMetadata
            {
                Id = string.Empty, // Will be generated by service
                Name = name ?? Path.GetFileNameWithoutExtension(path),
                Category = category ?? AssetCategory.Decorative,
                GlbPath = string.Empty, // Will be set by service
                PolyCount = 0, // Will be extracted by service
                License = license ?? "Unknown",
                Source = source ?? "Local Import",
                Author = author,
                Tags = tags ?? new Dictionary<string, string>(),
                FileSizeBytes = 0, // Will be set by service
                IsOptimized = false
            };

            var result = await assetService.ImportGlbAsync(path, metadata);

            Console.WriteLine("✅ Asset imported successfully!");
            Console.WriteLine($"   ID: {result.Id}");
            Console.WriteLine($"   Name: {result.Name}");
            Console.WriteLine($"   Category: {result.Category}");
            Console.WriteLine($"   Poly Count: {result.PolyCount:N0}");
            Console.WriteLine($"   File Size: {FormatFileSize(result.FileSizeBytes)}");
            Console.WriteLine($"   Storage Path: {result.GlbPath}");

            if (verbose && result.Bounds != null)
            {
                Console.WriteLine("   Bounding Box:");
                Console.WriteLine(
                    $"     Min: ({result.Bounds.Min.X:F2}, {result.Bounds.Min.Y:F2}, {result.Bounds.Min.Z:F2})");
                Console.WriteLine(
                    $"     Max: ({result.Bounds.Max.X:F2}, {result.Bounds.Max.Y:F2}, {result.Bounds.Max.Z:F2})");
                Console.WriteLine(
                    $"     Center: ({result.Bounds.Center.X:F2}, {result.Bounds.Center.Y:F2}, {result.Bounds.Center.Z:F2})");
                Console.WriteLine(
                    $"     Size: ({result.Bounds.Size.X:F2}, {result.Bounds.Size.Y:F2}, {result.Bounds.Size.Z:F2})");
            }

            return 0;
        }
        catch (Exception ex)
        {
            Console.WriteLine($"❌ Error importing asset: {ex.Message}");
            if (verbose)
            {
                Console.WriteLine($"   Stack trace: {ex.StackTrace}");
            }

            return 1;
        }
    }

    /// <summary>
    ///     Import multiple GLB files from a directory
    /// </summary>
    public async Task<int> ImportDirectoryAsync(
        string directoryPath,
        AssetCategory? category = null,
        string? license = null,
        string? source = null,
        bool recursive = false,
        bool verbose = false)
    {
        try
        {
            if (!Directory.Exists(directoryPath))
            {
                Console.WriteLine($"Error: Directory not found: {directoryPath}");
                return 1;
            }

            var searchOption = recursive ? SearchOption.AllDirectories : SearchOption.TopDirectoryOnly;
            var glbFiles = Directory.GetFiles(directoryPath, "*.glb", searchOption);

            if (glbFiles.Length == 0)
            {
                Console.WriteLine($"No GLB files found in {directoryPath}");
                return 0;
            }

            Console.WriteLine($"Found {glbFiles.Length} GLB file(s) to import...\n");

            var successCount = 0;
            var failureCount = 0;

            foreach (var file in glbFiles)
            {
                var fileName = Path.GetFileName(file);
                Console.Write($"Importing {fileName}... ");

                try
                {
                    var metadata = new AssetMetadata
                    {
                        Id = string.Empty,
                        Name = Path.GetFileNameWithoutExtension(file),
                        Category = category ?? AssetCategory.Decorative,
                        GlbPath = string.Empty,
                        PolyCount = 0,
                        License = license ?? "Unknown",
                        Source = source ?? "Local Import",
                        FileSizeBytes = 0,
                        IsOptimized = false
                    };

                    var result = await assetService.ImportGlbAsync(file, metadata);
                    Console.WriteLine($"✅ ({result.PolyCount:N0} polys, {FormatFileSize(result.FileSizeBytes)})");
                    successCount++;
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"❌ {ex.Message}");
                    failureCount++;
                }
            }

            Console.WriteLine("\n📊 Import Summary:");
            Console.WriteLine($"   ✅ Successful: {successCount}");
            Console.WriteLine($"   ❌ Failed: {failureCount}");
            Console.WriteLine($"   📁 Total: {glbFiles.Length}");

            return failureCount > 0 ? 1 : 0;
        }
        catch (Exception ex)
        {
            Console.WriteLine($"❌ Error importing directory: {ex.Message}");
            if (verbose)
            {
                Console.WriteLine($"   Stack trace: {ex.StackTrace}");
            }

            return 1;
        }
    }

    /// <summary>
    ///     List all imported assets
    /// </summary>
    public async Task<int> ListAssetsAsync(AssetCategory? category = null, bool verbose = false)
    {
        try
        {
            var assets = category.HasValue
                ? await assetService.GetAssetsByCategoryAsync(category.Value)
                : await assetService.GetAllAssetsAsync();

            if (assets.Count == 0)
            {
                Console.WriteLine("No assets found.");
                return 0;
            }

            Console.WriteLine($"Found {assets.Count} asset(s):\n");

            foreach (var asset in assets.OrderBy(a => a.Category).ThenBy(a => a.Name))
            {
                Console.WriteLine($"📦 {asset.Name}");
                Console.WriteLine($"   ID: {asset.Id}");
                Console.WriteLine($"   Category: {asset.Category}");
                Console.WriteLine($"   Poly Count: {asset.PolyCount:N0}");
                Console.WriteLine($"   File Size: {FormatFileSize(asset.FileSizeBytes)}");
                Console.WriteLine($"   License: {asset.License}");
                Console.WriteLine($"   Source: {asset.Source}");

                if (verbose)
                {
                    if (!string.IsNullOrEmpty(asset.Author))
                    {
                        Console.WriteLine($"   Author: {asset.Author}");
                    }

                    if (asset.Tags.Any())
                    {
                        Console.WriteLine(
                            $"   Tags: {string.Join(", ", asset.Tags.Select(t => $"{t.Key}={t.Value}"))}");
                    }

                    if (asset.Bounds != null)
                    {
                        Console.WriteLine(
                            $"   Bounds: {asset.Bounds.Size.X:F2} × {asset.Bounds.Size.Y:F2} × {asset.Bounds.Size.Z:F2}");
                    }
                }

                Console.WriteLine();
            }

            return 0;
        }
        catch (Exception ex)
        {
            Console.WriteLine($"❌ Error listing assets: {ex.Message}");
            if (verbose)
            {
                Console.WriteLine($"   Stack trace: {ex.StackTrace}");
            }

            return 1;
        }
    }

    /// <summary>
    ///     Delete an asset by ID
    /// </summary>
    public async Task<int> DeleteAssetAsync(string id, bool verbose = false)
    {
        try
        {
            var asset = await assetService.GetAssetByIdAsync(id);
            if (asset == null)
            {
                Console.WriteLine($"Asset not found: {id}");
                return 1;
            }

            Console.WriteLine($"Deleting asset: {asset.Name} ({id})");
            await assetService.DeleteAssetAsync(id);
            Console.WriteLine("✅ Asset deleted successfully!");

            return 0;
        }
        catch (Exception ex)
        {
            Console.WriteLine($"❌ Error deleting asset: {ex.Message}");
            if (verbose)
            {
                Console.WriteLine($"   Stack trace: {ex.StackTrace}");
            }

            return 1;
        }
    }

    // Helper methods

    private static string FormatFileSize(long bytes)
    {
        string[] sizes = ["B", "KB", "MB", "GB"];
        double len = bytes;
        var order = 0;
        while (len >= 1024 && order < sizes.Length - 1)
        {
            order++;
            len /= 1024;
        }

        return $"{len:0.##} {sizes[order]}";
    }
}
