#define Why_Guitar_Alchemist_	1
#define System_Requirements	2
#define How_to_buy_Guitar_Alchemist	3
#define The_main_window	4
#define The_options_dialog	5
#define The_fingerboard_options_page	6
#define The_theme_options_page	7
#define The_MIDI_options_page	8
#define View_selector	9
#define The_menu	10
#define The_fingerboard	11
#define The_status_bar	12
#define The_scale_selector_panel	13
#define The_scale_pattern_panel	14
#define The_matching_chords_panel	15
#define The_chord_selector_panel	16
#define The_chord_dictionnary_panel	17
#define The_matching_scale_panel	18
#define The_scales_view	19
#define The_chords_view	20
#define The_intervals	21
#define The_keys	22
#define The_major_scale_modes	23
#define The_melodic_minor_modes	24
#define The_harmonic_minor_modes	25
#define The_harmonic_major_modes	26
#define The_character_tones	27
