namespace GA.Business.Config

open YamlDotNet.Serialization
open YamlDotNet.Serialization.NamingConventions
open System
open System.Collections.Generic
open System.IO

/// Loader for AtonalModalFamilies.yaml — the bridge between GA.Domain.Core's
/// atonal ModalFamily catalog (ICV-keyed, ~200 families enumerated from
/// PitchClassSet.Items) and GA.Business.Config's Modes.yaml (tonal, 31 named
/// families). Generated by Demos/AtonalModalFamiliesGenerator.
///
/// Each atonal family carries:
///   - IntervalClassVector (string, the atonal invariant)
///   - FamilyName — imported from Modes.yaml when a member PC set matches,
///     else "Family-{ForteNumber}" (no coined names)
///   - ForteNumbers — one entry for most families; two for hexachord Z-pairs
///   - TonalSubfamilies — every Modes.yaml family that supplied at least one
///     mode (captures cases like Harmonic Minor + Harmonic Major sharing one ICV)
///   - Per-mode TonalAnalog + Aliases, preserved even when the mode came from
///     a non-dominant subfamily
module AtonalModalFamiliesConfig =

    type AtonalMode =
        { Position: int
          PitchClasses: string
          PitchClassSetId: int
          TonalAnalog: string option
          Aliases: string list }

    type AtonalModalFamily =
        { IntervalClassVector: string
          FamilyName: string
          ForteNumbers: string list
          TonalSubfamilies: string list
          NoteCount: int
          DistinctModeCount: int
          IsSymmetric: bool
          PrimeModeId: int
          Modes: AtonalMode list }

    // ── Internal YAML shape (CLIMutable for YamlDotNet) ──────────────────────

    [<CLIMutable>]
    type private YAtonalMode =
        { Position: int
          PitchClasses: string
          PitchClassSetId: int
          TonalAnalog: string
          Aliases: ResizeArray<string> }

    [<CLIMutable>]
    type private YAtonalFamily =
        { IntervalClassVector: string
          FamilyName: string
          ForteNumbers: ResizeArray<string>
          TonalSubfamilies: ResizeArray<string>
          NoteCount: int
          DistinctModeCount: int
          IsSymmetric: bool
          PrimeModeId: int
          Modes: ResizeArray<YAtonalMode> }

    [<CLIMutable>]
    type private YFile =
        { Families: ResizeArray<YAtonalFamily> }

    // ── Config discovery ─────────────────────────────────────────────────────

    let private findConfigPath () =
        let configName = "AtonalModalFamilies.yaml"

        let possiblePaths =
            [ Path.Combine(AppDomain.CurrentDomain.BaseDirectory, configName)
              Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "config", configName)
              Path.Combine(Environment.CurrentDirectory, configName)
              Path.Combine(Environment.CurrentDirectory, "Common", "GA.Business.Config", configName)
              // Test runners often live at bin/<Config>/<tfm>/
              Path.Combine(
                  AppDomain.CurrentDomain.BaseDirectory,
                  "..",
                  "..",
                  "..",
                  "..",
                  "Common",
                  "GA.Business.Config",
                  configName
              )
              Path.Combine(__SOURCE_DIRECTORY__, configName) ]

        possiblePaths |> List.tryFind File.Exists

    // ── Lazy-loaded, cached catalog ──────────────────────────────────────────

    let private toList (arr: ResizeArray<'T>) : 'T list =
        if isNull (box arr) then [] else arr |> List.ofSeq

    let private toStringOption (s: string) : string option =
        if isNull s || String.IsNullOrWhiteSpace(s) then None
        elif String.Equals(s, "null", StringComparison.OrdinalIgnoreCase) then None
        else Some s

    let private loadCatalog () : AtonalModalFamily list =
        match findConfigPath () with
        | Some path ->
            try
                let yaml = File.ReadAllText(path)

                let deserializer =
                    DeserializerBuilder()
                        .WithNamingConvention(PascalCaseNamingConvention.Instance)
                        .IgnoreUnmatchedProperties()
                        .Build()

                let data = deserializer.Deserialize<YFile>(yaml)

                if isNull (box data) || isNull (box data.Families) then
                    []
                else
                    data.Families
                    |> Seq.map (fun f ->
                        let modes : AtonalMode list =
                            if isNull (box f.Modes) then
                                []
                            else
                                f.Modes
                                |> Seq.map (fun m ->
                                    ({ Position = m.Position
                                       PitchClasses = if isNull m.PitchClasses then "" else m.PitchClasses
                                       PitchClassSetId = m.PitchClassSetId
                                       TonalAnalog = toStringOption m.TonalAnalog
                                       Aliases = toList m.Aliases } : AtonalMode))
                                |> List.ofSeq

                        ({ IntervalClassVector = if isNull f.IntervalClassVector then "" else f.IntervalClassVector
                           FamilyName = if isNull f.FamilyName then "" else f.FamilyName
                           ForteNumbers = toList f.ForteNumbers
                           TonalSubfamilies = toList f.TonalSubfamilies
                           NoteCount = f.NoteCount
                           DistinctModeCount = f.DistinctModeCount
                           IsSymmetric = f.IsSymmetric
                           PrimeModeId = f.PrimeModeId
                           Modes = modes } : AtonalModalFamily))
                    |> List.ofSeq
            with _ ->
                []
        | None -> []

    let private catalog = lazy (loadCatalog ())

    // ── Public API ───────────────────────────────────────────────────────────

    /// All atonal modal families in the catalog, ordered by NoteCount then ICV id
    /// (matches the order produced by the generator).
    let GetAll () : AtonalModalFamily seq =
        catalog.Value :> seq<_>

    /// Look up a family by its Interval Class Vector string (e.g. "<2 5 4 3 6 1>").
    /// Whitespace around angle brackets is tolerated.
    let TryGetByIntervalClassVector (icv: string) : AtonalModalFamily option =
        if isNull icv then
            None
        else
            let normalized = icv.Trim()

            catalog.Value
            |> List.tryFind (fun f ->
                String.Equals(f.IntervalClassVector, normalized, StringComparison.OrdinalIgnoreCase))

    /// Look up every family whose ForteNumbers list contains the given label.
    /// Returns a list because hexachord Z-pairs share Forte numbers across two
    /// distinct prime forms within the same ICV bucket.
    let TryGetByForteNumber (forte: string) : AtonalModalFamily list =
        if isNull forte then
            []
        else
            let target = forte.Trim()

            catalog.Value
            |> List.filter (fun f ->
                f.ForteNumbers
                |> List.exists (fun fn -> String.Equals(fn, target, StringComparison.OrdinalIgnoreCase)))

    /// Look up the (family, mode) pair whose mode name matches the given tonal
    /// analog (e.g. "Dorian" → Major Scale Family, mode 3). Returns None if no
    /// mode in any family has that tonal analog.
    let TryGetByTonalAnalog (name: string) : (AtonalModalFamily * AtonalMode) option =
        if isNull name then
            None
        else
            let target = name.Trim()

            catalog.Value
            |> List.tryPick (fun f ->
                f.Modes
                |> List.tryFind (fun m ->
                    match m.TonalAnalog with
                    | Some analog -> String.Equals(analog, target, StringComparison.OrdinalIgnoreCase)
                    | None -> false)
                |> Option.map (fun m -> (f, m)))

    /// Every family with a single distinct mode (symmetric sets — whole tone,
    /// diminished chord, augmented triad, chromatic, etc.).
    let GetSymmetricFamilies () : AtonalModalFamily seq =
        catalog.Value |> List.filter (fun f -> f.IsSymmetric) :> seq<_>

    /// Every family without a tonal analog in Modes.yaml — FamilyName is
    /// "Family-{ForteNumber}" and modes are positional only.
    let GetUnnamedFamilies () : AtonalModalFamily seq =
        catalog.Value
        |> List.filter (fun f -> f.FamilyName.StartsWith("Family-", StringComparison.Ordinal))
        :> seq<_>
