[Baglama.Greek]
Tuning = "D4 D5 A4 A4 D5 D5"

[Bajo.Quinto]
Tuning = "A2 A1 D3 D2 G2 G2 C3 C3 F3 F3"

[Bajo.Sexto]
Tuning = "E2 E1 A2 A1 D3 D2 G2 G2 C3 C3 F3 F3"

[Balalaika.Alto]
Tuning = "E3 E3 A3"

[Balalaika.Bass]
Tuning = "E2 A2 D3"

[Balalaika.Contrabass]
Tuning = "E1 A1 D2"

[Balalaika.Piccolo]
Tuning = "B4 E5 A5"

[Balalaika.Prima]
Tuning = "E4 E4 A4"

[Balalaika.Sekunda]
Tuning = "A3 A3 D4"

[Bandola.Central]
Tuning = "E3 E4 A3 A3 D3 D4 G3 G4"

[Bandola.AndinaColombiana]
FullName = "Andina Colombiana"
Tuning = "F#3 F#3 B3 B3 E4 E4 E4 A4 A4 A4 D5 D5 D5 G5 G5 G5"

[Bandola.Guayanesa]
Tuning = "G3 G4 D3 D4 A4 A4 E5 E5"

[Bandola.Llanera]
Tuning = "A3 D4 F#4 B4"

[Bandola.Oriental]
Tuning = "G3 G3 D4 D4 A4 A4 E5 E5"

[Bandolim.Standard]
Tuning = "G3 G3 D4 D4 A4 A4 E5 E5"

[Bandora.Standard]
Tuning = "G4 C2 D2 G2 C3 E3 A3"

[Bandurria.Standard]
Tuning = "G#3 G#3 C#4 C#4 F#4 F#4 B4 B4 E5 E5 A5 A5"

[Bandurria.Peruvian]
Tuning = "D5 D4 D5 D5 G4 G3 G4 G4 B4 B4 B4 B4 E5 E5 E5 E5"

[Bandurria.Phillipines]
Tuning = "F#3 B3 B3 E4 E4 A4 A4 A4 D5 D5 D5 G5 G5 G5"

[Banjo.Cello]
Tuning = "C2 G2 D3 A3"

[Banjo.TenorJazz]
FullName = "Tenor (Jazz)"
Tuning = "C3 G3 D4 A4"

[Banjo.TenorIrish]
FullName = "Tenor (Irish)"
Tuning = "G2 D3 A3 E3"

[Banjo.Plectrum]
Tuning = "C3 G3 B3 D4"

[Banjo.Bluegrass5Strings]
FullName = "5 strings Bluegrass"
Tuning = "G4 D3 G3 B3 D4"

[Banjo.CTuning5Strings]
FullName = "5 strings C Tuning"
Tuning = "G4 C3 G3 B3 D4"

[Banjolin.Standard]
Tuning = "G3 D4 A5 E5"

[Banjourine.Standard]
Tuning = "C5 G3 C4 E3 G4"

["Baritone Guitar".Standard1]
Tuning = "B1 E2 A2 D3 F#3 B3"

["Baritone Guitar".Standard2]
Tuning = "A1 D2 G2 C3 E3 A3"

["Baritone Guitar"."Octave Lower"]
Tuning = "E1 A1 D2 G2 B2 E3"

["Bass Guitar".Standard]
Tuning = "E1 A1 D2 G2"

["Bass Guitar".FiveStrings]
FullName = "5 strings"
Tuning = "B0 E1 A1 D2 G2"

["Bass Guitar".SixStrings]
FullName = "6 strings"
Tuning = "B0 E1 A1 D2 G2 C3"

[Bordonua.Standard]
Tuning = "A2 A3 D4 D3 F#3 F#4 B3 B3 E4 E4"

[Bouzouki.GreekTetrachordo]
FullName = "Greek Tetrachordo"
Tuning = "C3 C4 F3 F4 A3 A3 D4 D4"

[Bouzouki.GreekTrichordo]
FullName = "Greek Trichordo"
Tuning = "D3 D4 A3 A3 D4 D4"

[Bouzouki.IrishGDADOctave]
FullName = "Irish GDAD (Oct.)"
Tuning = "G3 G2 D4 D3 A3 A3 D4 D4"

[Bouzouki.IrishGDADPairs]
FullName = "Irish GDAD (Pairs)"
Tuning = "G2 G2 D3 D3 A3 A3 D4 D4"

[Bouzouki.IrishFifthsOctave]
FullName = "Irish 5ths (Oct.)"
Tuning = "G3 G2 D4 D3 A3 A3 E4 E4"

[Bouzouki.IrishFifthsPairs]
FullName = "Irish 5ths (Pairs)"
Tuning = "G2 G2 D3 D3 A3 A3 E4 E4"

[Bouzouki.IrishModalDOctaves]
FullName = "Irish Modal D (Octaves)"
Tuning = "A3 A2 D4 D3 A3 A3 D4 D4"

[Bouzouki."IrishModalD(UnisonPairs"]
FullName = "Irish Modal D (Unison Pairs)"
Tuning = "A2 A2 D3 D3 A3 A3 D4 D4"

[Braguinha.Standard]
Tuning = "D4 G4 B4 D5"

[Cavaquinho.Standard]
Tuning = "D4 G4 B4 D5"

[Cavaquinho.AMajor]
FullName = "A Major"
Tuning = "A4 A4 C#5 E5"

[Cavaquinho.AMajorV2]
FullName = "A Major (version 2)"
Tuning = "E4 A4 C#5 E5"

[Cavaquinho.CMajor]
FullName = "C Major"
Tuning = "G4 C5 E5 G5"

[Cavaquinho.GMajor]
FullName = "G Major"
Tuning = "G4 G4 B4 D5"

[Chanzy.Standard]
Tuning = "F2 C3 F3"

[Charango.Standard]
Tuning = "G4 G4 C4 C4 E5 E4 A4 A4 E5 E5"

[Charango.Ranka]
Tuning = "D4 D4 A4 A4 G4 G4 C5 C5 G5 G6"

[Charangon.Tuning1]
Tuning = "F6 C4 C4 F4 F4 A5 A4 D5 D5 A5 A5"

[Charangon.Tuning2]
Tuning = "G6 D4 D4 G4 G4 B5 B4 E5 E5 B5 B5"

["Chitarra Battente".Standard]
Tuning = "A3 D4 G3 B3 E4"

[Chonguri.DMinor]
Tuning = "D2 F2 D3 A2"

[Chonguri.FMajor]
Tuning = "F3 A3 F4 C4"

[Cistre.Standard]
Tuning = "E2 A2 D3 D3 E3 E3 A3 A3 C#4 C#4 E4 E4"

[Cittern.Bell]
Tuning = "B3 B3 D4 D4 F4 F4 A4 A4 D5 D5"

[Cittern."Celtic 5ths Longscale"]
Tuning = "C2 C2 G2 G2 D3 D3 A3 A3 E4 E4"

[Cittern."Celtic Longscale 1"]
Tuning = "C2 C2 G2 G2 D3 D3 G3 G3 D4 D4"

[Cittern."Celtic Longscale 2"]
Tuning = "D2 D2 A2 A2 E3 E3 A3 A3 E4 E4"

[Cittern."Celtic Shortscale"]
Tuning = "G2 G2 D3 D3 A3 A3 D4 D4 A4 A4"

[Cittern."Celtic 5ths Shortscale"]
Tuning = "G2 G2 D3 D3 A3 A3 E4 E4 B4 B4"

[Cittern."Celtic Irish"]
Tuning = "D2 D2 G2 G2 D3 D3 A3 A3 D4 D4"

[Cittern."Celtic Mandocello Longscale"]
Tuning = "C2 C2 G2 G2 D3 D3 A3 A3 D4 D4"

[Cittern."Celtic Mandocello Shortscale"]
Tuning = "G2 G2 D3 D3 A3 A3 E4 E4 A4 A4"

[Cittern."Celtic Modal C Longscale"]
Tuning = "C2 C2 G2 G2 C3 C3 G3 G3 C4 C4"

[Cittern."Celtic Modal C Shortscale"]
Tuning = "G2 G2 C3 C3 G3 G3 C4 C4 G4 G4"

[Cittern."Celtic Modal D Longscale"]
Tuning = "D2 D2 A2 A2 D3 D3 A3 A3 D4 D4"

[Cittern."Celtic Modal D Shortscale"]
Tuning = "A2 A2 D3 D3 A3 A3 D4 D4 A4 A4"

[Cittern."Celtic Modal F Shortscale"]
Tuning = "F2 F2 C3 C3 F3 F3 C4 C4 F4 F4"

[Cittern."Celtic Modal G Longscale"]
Tuning = "D2 D2 G2 G2 D3 D3 G3 G3 D4 D4"

[Cittern."Celtic Modal G Shortscale"]
Tuning = "G2 G2 D3 D3 G3 G3 D4 D4 G4 G4"

[Cittern."Celtic Modal A Longscale"]
Tuning = "E2 E2 A2 A2 E3 E3 A3 A3 E4 E4"

[Cittern."16th/17th Century"]
Tuning = "B3 B3 G4 G4 G3 D4 D4 E4 E4"

[Cittern."French Tuning"]
Tuning = "A4 A4 G4 G4 G3 D4 D4 E4 E4"

[Cuatro."Puerto Rican"]
Tuning = "B3 B2 E4 E3 A3 A3 D4 D4 G4 G4"

[Cuatro.Venezuelan]
Tuning = "A3 D4 F#4 B3"

[Cumbus."Dan Tyba"]
Tuning = "G3 C4 D4 G4"

["Dobro or Resophonic".Standard]
Tuning = "G2 B2 D3 G3 B3 D4"

[Domra.Alto]
Tuning = "E3 A3 D4"

[Domra.Bass]
Tuning = "E2 A2 D3"

[Domra.ContrabassMajor]
Tuning = "A1 D2 G2"

[Domra.ContrabassMinor]
Tuning = "E1 A1 D2"

[Domra.Mezzosoprano]
Tuning = "B3 E4 A4"

[Domra.Piccolo]
Tuning = "B4 E5 A5"

[Domra.Prima]
Tuning = "E4 A4 D5"

[Domra.Tenor]
Tuning = "B2 E3 A3"

[Domra.UkrainianPrima]
FullName = "Ukrainian Prima"
Tuning = "G3 D4 A4 E5"

[Dulcimer.AeolianModeDMinor]
FullName = "Aeolian Mode D Minor"
Tuning = "C4 C4 A3 D3"

[Dulcimer.AeolianModeCMinor]
FullName = "Aeolian Mode C Minor"
Tuning = "Bb3 Bb3 G3 C3"

[Dulcimer.DorianModeDMinor]
FullName = "Dorian Mode D Minor"
Tuning = "G3 G3 A3 D3"

[Dulcimer.DorianModeEMinor]
FullName = "Dorian Mode E Minor"
Tuning = "A3 A3 B3 E3"

[Dulcimer.IonianKeyOfD]
FullName = "Ionian Key of D"
Tuning = "A3 A3 A3 D3"

[Dulcimer.IonianKeyOfC]
FullName = "Ionian Key of C"
Tuning = "G3 G3 G3 C3"

[Dulcimer.LocrianModeOfCSharpMinor]
FullName = "Locrian Mode C# Minor"
Tuning = "A3 A3 G#3 C#3"

[Dulcimer.LocrianModeDMinor]
FullName = "Locrian Mode D Minor"
Tuning = "Bb3 Bb3 A3 D3"

[Dulcimer.LydianModeCAndMore]
FullName = "Lydian Mode C and More"
Tuning = "D4 D4 G3 C3"

[Dulcimer.LydianMode]
FullName = "Lydian Mode"
Tuning = "Bb C4 C4 F3 Bb2"

[Dulcimer.MixolydianMode]
FullName = "Mixolydian Mode"
Tuning = "D4 D4 A3 D3"

[Dulcimer.PhrygianMode]
FullName = "Phrygian Mode"
Tuning = "Eb4 Eb4 G3 C3"

[EnglishGuittar.Standard]
Tuning = "C3 E3 G3 G3 C4 C4 E4 E4 G4 G4"

[Gekkin.Standard]
Tuning = "A3 D4 D4 D5"

[Ghita.Standard]
Tuning = "C3 F3 C4 G4 C5"

[Gittern.Standard]
Tuning = "D4 G4 D5 G5"

[Grajappi.Standard]
Tuning = "F2 F2 B2 B2"

[Guitar.Standard]
Tuning = "E2 A2 D3 G3 B3 E4"

[Guitar.DADGAD]
Tuning = "D2 A2 D3 G3 A3 D4"

[Guitar."Double Drop D"]
Tuning = "D2 A2 D3 G3 B3 D4"

[Guitar.DropD]
FullName = "Drop D"
Tuning = "D2 A2 D3 G3 B3 E4"

[Guitar.OpenCMajor]
FullName = "Open C Major"
Tuning = "C2 G2 C3 G3 C3 E4"

[Guitar.OpenDMajor]
FullName = "Open D Major"
Tuning = "D2 A2 D3 F#3 A3 D4"

[Guitar.OpenEMajorV1]
FullName = "Open E - 1 Major"
Tuning = "E2 B2 E3 G#3 B3 E4"

[Guitar.OpenEMajorV2]
FullName = "Open E - 2 Minor"
Tuning = "E2 B2 E3 G3 B3 E4"

[Guitar.OpenGMajorV1]
FullName = "Open G - 1 Major"
Tuning = "D2 G2 D3 G3 B3 D4"

[Guitar.OpenGMinorV2]
FullName = "Open G - 2 Minor"
Tuning = "D2 G2 D3 G3 Bb3 D4"

[Guitar.OpenAMajor]
FullName = "Open A Major"
Tuning = "E2 A2 E3 A3 C#3 E4"

[Guitar.Renaissance]
Tuning = "G3 G4 C4 C4 E4 E4 A4"

[Guitar.Baroque1]
FullName = "Baroque 1"
Tuning = "A3 A3 D4 D4 G3 G3 B3 B3 E4 E4"

[Guitar.Baroque2]
FullName = "Baroque 2"
Tuning = "A3 A3 D4 D3 G3 G3 B3 B3 E4 E4"

[Guitar.TwelveStrings]
FullName = "12-String"
Tuning = "E2 E3 A2 A3 D3 D4 G3 G4 B3 B3 E4 E4"

["Guitar Banjo".Standard]
Tuning = "E2 A2 D3 G3 B3 E4"

["Guitar Decacorde".Standard]
Tuning = "C2 D2 E2 F2 G2 A2 D3 G3 B3 E4"

["Guitarra de Golpe".Standard]
Tuning = "D3 G3 C4 E3 A3"

["Guitarro or Guitarrico".Standard]
Tuning = "B4 F#4 D5 A5 E5"

["Guitarrón".Standard]
Tuning = "A1 D2 G2 C3 E3 A2"

[Halszither.Krienser]
Tuning = "G2 G2 D3 D3 G3 G3 B3 B3 D4 D4"

[Harzzither.Standard]
Tuning = "G3 G3 C4 C4 E4 E4 G4 G4"

["Hawaiian Guitar"."Tuning 1"]
Tuning = "E2 A2 E3 A3 C#4 E4"

["Hawaiian Guitar"."Tuning 2"]
Tuning = "G2 B2 D3 G3 B3 D4"

[Huapanguera.Standard]
Tuning = "Huapanguera"

[Jarana.Huasteca]
Tuning = "G3 B3 D4 F#4 A4"

[Jarana.Jarocha]
Tuning = "A3 D4 D4 G3 G4 B3 B3 E4"

[Laud.Standard]
Tuning = "G#2 G#2 C#3 C#3 F#3 F#3 B3 B3 E4 E4 A4 A4"

[Lavta.Standard]
Tuning = "C2 C2 G2 G2 D3 D3 A3 A3"

[Liuqin.Standard]
Tuning = "G3 D4 G4 D5"

[Lute.BaroqueDMinor]
FullName = "Baroque D Minor"
Tuning = "A2 D3 F3 A3 D4 F4"

[Lute.Medieval]
Tuning = "G2 G2 C3 C3 F3 F3 A3 A3 D4 D4 G4 G4"

[Lute.RenaissanceTenor]
FullName = "Renaissance Tenor"
Tuning = "D2 F2 G2 C3 F3 A3 D4 G4"

[Mandobass.Standard]
Tuning = "E1 A1 D2 G2"

[Mandocello.Standard]
Tuning = "C2 C2 G2 G2 D3 D3 A3 A3"

[Mandola.Tenor]
Tuning = "C3 C3 G3 G3 D4 D4 A4 A4"

[Mandolin.Standard]
Tuning = "G3 G3 D4 D4 A4 A4 E5 E5"

[Mandolin.FiveCourse]
FullName = "5 Course"
Tuning = "C3 C3 G3 G3 D4 D4 A4 A4 E5 E5"

[Mandolin.ElectricFiveStrigs]
FullName = "Electric 5-String"
Tuning = "C3 G3 D4 A4 E5"

[Mandolin.Cremona]
Tuning = "G3 D4 A4 E5"

[Mandolin.Genuese]
Tuning = "E3 E3 A3 A3 D3 D4 G4 G4 B4 B4 E5 E5"

[Mandolin.Neopolitan]
Tuning = "G3 G4 D4 D4 A4 A4 E5 E5"

[Mandolin.Piccolo]
Tuning = "C4 C4 G4 G4 D5 D5 A5 A5"

[Mandolin.Banjo]
Tuning = "G3 G3 D4 D4 A5 A5 E5 E5"

[Mandolino.Standard]
Tuning = "G3 G3 B3 B3 E4 E4 A4 A4 D5 D5 G5 G5"

[Mandolino.Lombardo]
Tuning = "G3 B3 E4 A4 D5 G5"

[Mandore.ModalC]
FullName = "Modal C"
Tuning = "C4 G4 C5 G5"

[Mandore.ModalG]
FullName = "Modal G"
Tuning = "G3 D4 G4 D5"

[Mandore.French]
Tuning = "E2 A2 D3 G3 B3 E4"

[MandriolaOrTricordia.Standard]
Tuning = "G2 G3 G3 D3 D4 D4 A3 A4 A4 E4 E5 E5"

[MandriolaOrTricordia."Unison pairs"]
Tuning = "G3 G3 G3 D4 D4 D4 A4 A4 A4 E5 E5 E5"

[Mejorana.Standard]
Tuning = "D4 A4 A3 B3 E4"

[Mondol.Standard]
Tuning = "E2 E2 A2 A2 D3 D3 G3 G3 B3 B3"

[OctaveGuitar.Standard]
Tuning = "E3 A3 D4 G4 B5 E5"

[Panduri.E]
Tuning = "E3 B3 A4"

[Panduri.G]
Tuning = "G3 A3 C4"

["Pedal Steel Guitar".T1]
Tuning = "C6 C2 F2 2 C3 E3 G3 A3 C4 E4 G4"

["Pedal Steel Guitar".T2]
Tuning = "E9 B2 D3 3 F#3 G#3 B3 E4 G#4 Eb4 F#4"

["Pedal Steel Guitar".UniversalTwelveStrings]
FullName = "Universal 12 Strings"
Tuning = "Bb2 Eb2 G2 Bb2 D3 F3 G3 Bb3 D4 F4 G4 E4"

[Phin.Standard]
Tuning = "G4 D4 A4"

[Pipa.Standard]
Tuning = "A2 D2 G3 A3"

[PortugueseGuitarra.Coimbra]
Tuning = "C3 C2 G3 G2 A3 A2 D3 D3 G3 G3 A3 A3"

[PortugueseGuitarra.Lisboa]
Tuning = "D3 D2 A3 A2 B3 B2 E3 E3 A3 A3 B3 B3"

["Rajão".Standard]
Tuning = "D4 G4 C4 E4 A4 A4"

[Ramkie.Standard]
Tuning = "C3 F3 A3 C4"

[Requinto.Standard]
Tuning = "A2 D3 G3 C4 E4 A4"

[Requinto.FourStringsV1]
FullName = "4 strings - 1"
Tuning = "G2 A2 D3 G3"

[Requinto.FourStringsV2]
FullName = "4 strings - 2"
Tuning = "C2 D2 G2 C3"

[Requinto.FiveStrings]
FullName = "5 Strings"
Tuning = "E2 A2 D3 G3 C3"

[Ronroco.Standard]
Tuning = "G3 G3 C3 C3 E4 E3 A3 A3 E4 E4"

[Ruan.Soprano]
Tuning = "G2 D3 A3 E4"

[Ruan.Tenor]
Tuning = "C2 G2 D3 A3"

[Ruan.Zhong]
Tuning = "G2 D2 G3 D3"

[RussianGuitar.Standard]
Tuning = "D2 G2 B2 D3 G3 B3 D4"

[Saz.AzeriOrQopuz]
FullName = "Azeri/Qopuz"
Tuning = "D4 D4 D4 G3 G3 C4 C4 C4"

[Saz.BaglamaBozukDuzenSixStrings]
FullName = "Baglama Bozuk Duzen 6 String"
Tuning = "G2 G3 D2 D3 A2 A3"

[Saz.BaglamaBozukDuzenSevenStrings]
FullName = "Baglama Bozuk Duzen 7 String"
Tuning = "Tuning G2 G3 D2 D3 A2 A3 A3"

[Seis.PuertoRican]
FullName = "Puerto Rican"
Tuning = "F#3 F#2 B3 B2 E4 E3 A3 A3 D4 D4 G4 G4"

[Seis.PuertoRicanGuitarTuning]
FullName = "Puerto Rican Guitar Tuning"
Tuning = "F#3 F#2 B3 B2 E4 E3 A3 A3 C#4 C#4 F#4 F#4"

[Setar.Standard]
Tuning = "C3 C4 G3 C4"

[Sitar.Standard]
Tuning = "C5 C4 G3 C2 G2 C3 F3"

[SopranoGuitar.Standard]
Tuning = "E3 A4 D4 G4 B4 E5"

[Sovacon.Standard]
Tuning = "G2 D3 A3 B2"

[Strumstick.Standard]
Tuning = "G3 D4 G4"

[Tambur.Yali]
Tuning = "D2 D2 A2 A2 D3 D3"

[Tamburitza.Brac]
Tuning = "E2 A2 D3 G3"

[Tamburitza.Bugarija]
Tuning = "G2 B2 D3 G3 G3"

[Tar.Standard]
Tuning = "C3 C4 G3 G3 C4 C4"

[Tar.TarAzeriOrCaucasus]
FullName = "Tar - Azeri/Caucasus"
Tuning = "C4 C4 C5 C5 G2 C3 C4 G3 G3 C4 C4"

[TaroPatch.Standard]
Tuning = "G3 G4 C4 C3 C4 E4 E4 A4 A4"

[TenorGuitar.Standard]
Tuning = "C3 G3 D4 A4"

[TenorGuitar.Irish]
Tuning = "G2 D3 A3 E3"

[Timple.Standard]
Tuning = "G4 C5 E4 A4 D5"

[Tiple.Chilean]
Tuning = "D4 D3 D4 G4 G3 G4 B3 B3 B3 E4 E4 E4"

[Tiple.Columbian]
Tuning = "D4 D3 D4 G4 G3 G4 B3 B3 B3 E4 E4 E4"

[Tiple.Doliente]
Tuning = "E3 A3 D4 G4 C5"

[Tiple."Martin Style"]
Tuning = "A3 A4 D4 D3 D4 F#4 F#3 F#4 B4 B4"

[Tiple.Requinto]
Tuning = "D4 D4 G4 G4 G4 B4 B4 B4 E4 E4"

[TresCubano.CMajor]
Tuning = "G4 G3 C4 C4 E4 E3"

[TresCubano.DMajor]
Tuning = "A4 A3 D4 D4 F#4 F#4"

[Tzouras.Standard]
Tuning = "D3 D4 A3 A3 D4 D4"

[Ukulele.SopranoConcertAndTenorC]
FullName = "Soprano C, Concert & Tenor C"
Tuning = "C6 G4 C4 E4 A4"

[Ukulele.SopranoConcertAndTenorD]
FullName = "Soprano, Concert & Tenor D"
Tuning = "D6 A4 D4 F#4 B4"

[Ukulele.Baritone]
Tuning = "D4 G3 B4 E4"

[Ukulele.Tahitian]
Tuning = "G4 G4 C5 C5 E5 E5 A4 A4"

[Ukulele.BanjoOrBanjoleteC]
FullName = "Ukulele Banjo or Banjolele C"
Tuning = "C6 G4 C4 E4 A4"

[Ukulele.BanjoOrBanjoleteD]
FullName = "Ukulele Banjo or Banjolele D"
Tuning = "D6 A4 D4 F#4 B4"

[Vihuela.Standard]
Tuning = "A3 D4 G4 B3 E4"

[Viola.Amarantina]
FullName = "Viola Amarantina"
Tuning = "D3 D2 A3 A2 B3 B2 E3 E3 A3 A3"

[Viola.Beiroa]
FullName = "Viola Beiroa"
Tuning = "D3 D3 A3 A2 D3 D2 G3 G2 B3 B3 D3 D3"

[Viola.Braguesa]
FullName = "Viola Braguesa"
Tuning = "C3 C2 G3 G2 A3 A2 D3 D3 G3 G3"

[Viola.Caipira]
FullName = "Viola Caipira"
Tuning = "A3 A2 D4 D2 F#4 F#3 A3 A3 D4 D4"

[Viola."Campaniça"]
FullName = "Viola Campaniça"
Tuning = "C3 C2 F3 F2 C3 C3 E3 E3 G3 G3"

[Viola.DaTerra]
FullName = "Viola da Terra"
Tuning = "A4 A4 A4 D4 D4 D3 G3 G3 B3 B3 D4 D4"

[Viola.DeArame]
FullName = "Viola de Arame"
Tuning = "G3 G2 D3 D2 G3 G3 B3 D3 D3"

[Viola.DeCocho1]
FullName = "Viola de Cocho 1"
Tuning = "G3 D3 E3 A3 D4"

[Viola."DeCocho 2"]
FullName = "Viola de Cocho 2"
Tuning = "G3 C3 E3 A3 D4"

[Viola.DeDizCordas]
FullName = "Viola de Diz Cordas"
Tuning = "A3 A3 D3 D4 G3 G3 B3 B3 E4 E4"

[Viola.Sertaneja]
FullName = "Viola Sertaneja"
Tuning = "A3 A2 D4 D2 F#4 F#3 A3 A3 D4 D4"

[Viola.Toeira]
FullName = "Viola Toeira"
Tuning = "A3 A3 A3 D3 D3 D2 G3 G2 B3 B3 E3 E3"

["ViolãoDeSeteCordas".Standard]
Tuning = "B1 E2 A2 D3 G3 B3 E4"

[Walaycho.StandardF]
Tuning = "F6 C4 C4 F4 F4 A5 A4 D5 D5 A5 A5"

[Walaycho.StandardG]
Tuning = "G6 D4 D4 G4 G4 B5 B4 E5 E5 B5 B5"

[Waldzither.Hamburger]
Tuning = "C3 G3 G3 C4 C4 E4 E4 G4 G4"

[Waldzither."Thüringer"]
Tuning = "C3 G3 G3 C4 C4 E4 E4 G4 G4"

[YuehChinOrYuehQin.Standard]
Tuning = "G3 D4 G4 D5"

[Zister."Thüringer"]
Tuning = "C3 G3 G3 C4 C4 E4 E4 G4 G4"

["Angelique (Theorbo)".Standard]
Tuning = "D2 E2 F2 G2 A2 B2 C3 D3 E3 F3 G3 A3 B3 C4 D4 E4"

[Archlute."14 Course"]
Tuning = "F2 G2 A2 Bb2 C3 D3 E3 F3 G3 C4 F4 A4 D5 G5"

[Bandolin.Ecuadorean]
Tuning = "E5 E4 E5 A5 A4 A5 D5 D4 D5 F5 F5 F5 B5 B5 B5"

[BaroqueLute.Standard]
Tuning = "A2 B2 C3 D3 E3 F3 G3 A3 D4 F4 A4 D5 F5"

["GuitarrónChileno".Standard]
Tuning = "F#5 A4 D4 D4 D3 D3 D2 G4 G4 G4 G3 G3 C4 C4 C3 C2 E4 E4 E4 A4 A4 A4 G4 B4"

[LaudPhillipines.Standard]
Tuning = "F#2 B2 B2 E3 E3 A3 A3 A3 D4 D4 D4 G4 G4 G4"

[LiutoAttiorbatoTheorbo.Standard]
Tuning = "F1 F2 G1 G2 A1 A2 B1 B2 C2 C3 D2 D3 E2 E3 F2 F2 G2 G2 C3 C3 F3 F3 A3 A3 D4 D4 G4"

[Octavina.Standard]
Tuning = "F#2 B2 B2 E3 E3 A3 A3 A3 D4 D4 D4 G4 G4 G4"

["SächsischeTheorbenzister".Standard]
Tuning = "B2 C2 D3 E3 F3 G3 A3 B3 C4 C4 F4 F4 A4 A4 C4 C4"

[SwedishLute.Standard]
Tuning = "A2 B2 C#3 D3 E3 F#3 G3 A3 B3 C#4 D4 E4 A4 C#5 E5"

[TheorboFifteenCourse.Standard]
Tuning = "F2 G2 A2 B2 C3 D3 E3 F3 G3 A3 D4 G4 B4 E4 A4"

[ViolaDaTerceiraFifteenStrings.Standard]
Tuning = "E3 E3 E2 A3 A3 A2 D3 D3 D2 G3 G2 B3 B3 E3 E3"