Baglama:
    Greek: 
       Tuning: D4 D5 A4 A4 D5 D5
Bajo:
    Quinto: 
       Tuning: A2 A1 D3 D2 G2 G2 C3 C3 F3 F3
    Sexto: E2 E1 A2 A1 D3 D2 G2 G2 C3 C3 F3 F3
Balalaika:
    Alto: 
        Tuning: E3 E3 A3
    Bass: 
        Tuning: E2 A2 D3
    Contrabass: 
        Tuning: E1 A1 D2
    Piccolo: B4 E5 A5
    Prima: E4 E4 A4
    Sekunda: A3 A3 D4
Bandola:
    Central: E3 E4 A3 A3 D3 D4 G3 G4
    Andina Colombiana: F#3 F#3 B3 B3 E4 E4 E4 A4 A4 A4 D5 D5 D5 G5 G5 G5
    Guayanesa: G3 G4 D3 D4 A4 A4 E5 E5
    Llanera: A3 D4 F#4 B4
    Oriental: G3 G3 D4 D4 A4 A4 E5 E5    
Bandolim:
    Standard: G3 G3 D4 D4 A4 A4 E5 E5
Bandora:
    Standard: G4 C2 D2 G2 C3 E3 A3
Bandurria:
    Standard: G#3 G#3 C#4 C#4 F#4 F#4 B4 B4 E5 E5 A5 A5
    Peruvian: D5 D4 D5 D5 G4 G3 G4 G4 B4 B4 B4 B4 E5 E5 E5 E5
    Phillipines: F#3 B3 B3 E4 E4 A4 A4 A4 D5 D5 D5 G5 G5 G5
Banjo:
    Cello: C2 G2 D3 A3
    Tenor: (Jazz) C3 G3 D4 A4
    Tenor (Irish): G2 D3 A3 E3
    Plectrum: C3 G3 B3 D4
    5 strings Bluegrass: G4 D3 G3 B3 D4
    5 strings C Tuning: G4 C3 G3 B3 D4
Banjolin:
    Standard: G3 D4 A5 E5
Banjourine:
    Standard: C5 G3 C4 E3 G4
Baritone Guitar:
    Standard 1: B1 E2 A2 D3 F#3 B3
    Standard 2: A1 D2 G2 C3 E3 A3
    Octave Lower: E1 A1 D2 G2 B2 E3
Bass Guitar:
    Standard: E1 A1 D2 G2
    5 strings: B0 E1 A1 D2 G2
    6 strings: B0 E1 A1 D2 G2 C3
Bordonua:
    Standard: A2 A3 D4 D3 F#3 F#4 B3 B3 E4 E4
Bouzouki:
    Greek Tetrachordo: C3 C4 F3 F4 A3 A3 D4 D4
    Greek Trichordo: D3 D4 A3 A3 D4 D4
    Irish GDAD (Oct.): G3 G2 D4 D3 A3 A3 D4 D4
    Irish GDAD (Pairs): G2 G2 D3 D3 A3 A3 D4 D4
    Irish 5ths (Oct.): G3 G2 D4 D3 A3 A3 E4 E4
    Irish 5ths (Pairs): G2 G2 D3 D3 A3 A3 E4 E4
    Irish Modal D (Octaves): A3 A2 D4 D3 A3 A3 D4 D4
    Irish Modal D (Unison Pairs): A2 A2 D3 D3 A3 A3 D4 D4
Braguinha:
    Standard: D4 G4 B4 D5
Cavaquinho:
    Standard: D4 G4 B4 D5
    A Major: A4 A4 C#5 E5
    A Major (version 2): E4 A4 C#5 E5
    C Major: G4 C5 E5 G5
    G Major: G4 G4 B4 D5
Chanzy:
    Standard: F2 C3 F3
Charango:
    Standard: G4 G4 C4 C4 E5 E4 A4 A4 E5 E5
    Ranka: D4 D4 A4 A4 G4 G4 C5 C5 G5 G6
Charangon:
    1: F6 C4 C4 F4 F4 A5 A4 D5 D5 A5 A5
    2: G6 D4 D4 G4 G4 B5 B4 E5 E5 B5 B5
Chitarra Battente:
    Standard: A3 D4 G3 B3 E4
Chonguri:
    D Minor: D2 F2 D3 A2
    F Major: F3 A3 F4 C4
Cistre:
    Standard: E2 A2 D3 D3 E3 E3 A3 A3 C#4 C#4 E4 E4
Cittern:
    Bell: B3 B3 D4 D4 F4 F4 A4 A4 D5 D5
    Celtic 5ths Longscale: C2 C2 G2 G2 D3 D3 A3 A3 E4 E4
    Celtic Longscale 1: C2 C2 G2 G2 D3 D3 G3 G3 D4 D4
    Celtic Longscale 2: D2 D2 A2 A2 E3 E3 A3 A3 E4 E4
    Celtic Shortscale: G2 G2 D3 D3 A3 A3 D4 D4 A4 A4
    Celtic 5ths Shortscale: G2 G2 D3 D3 A3 A3 E4 E4 B4 B4
    Celtic Irish: D2 D2 G2 G2 D3 D3 A3 A3 D4 D4
    Celtic Mandocello Longscale: C2 C2 G2 G2 D3 D3 A3 A3 D4 D4
    Celtic Mandocello Shortscale: G2 G2 D3 D3 A3 A3 E4 E4 A4 A4
    Celtic Modal C Longscale: C2 C2 G2 G2 C3 C3 G3 G3 C4 C4
    Celtic Modal C Shortscale: G2 G2 C3 C3 G3 G3 C4 C4 G4 G4
    Celtic Modal D Longscale: D2 D2 A2 A2 D3 D3 A3 A3 D4 D4
    Celtic Modal D Shortscale: A2 A2 D3 D3 A3 A3 D4 D4 A4 A4
    Celtic Modal F Shortscale: F2 F2 C3 C3 F3 F3 C4 C4 F4 F4
    Celtic Modal G Longscale: D2 D2 G2 G2 D3 D3 G3 G3 D4 D4
    Celtic Modal G Shortscale: G2 G2 D3 D3 G3 G3 D4 D4 G4 G4
    Celtic Modal A Longscale: E2 E2 A2 A2 E3 E3 A3 A3 E4 E4
    16th/17th Century: B3 B3 G4 G4 G3 D4 D4 E4 E4
    French Tuning: A4 A4 G4 G4 G3 D4 D4 E4 E4
Cuatro:
    Puerto Rican: B3 B2 E4 E3 A3 A3 D4 D4 G4 G4
    Venezuelan: A3 D4 F#4 B3
Cumbus:
    Dan Tyba: G3 C4 D4 G4
Dobro or Resophonic:
    Standard: G2 B2 D3 G3 B3 D4
Domra:
    Alto: E3 A3 D4
    Bass: E2 A2 D3
    Contrabass Major Tuning: A1 D2 G2
    Contrabass Minor Tuning: E1 A1 D2
    Mezzosoprano: B3 E4 A4
    Piccolo: B4 E5 A5
    Prima: E4 A4 D5
    Tenor: B2 E3 A3
    Ukrainian Prima: G3 D4 A4 E5
Dulcimer:
    Aeolian Mode D Minor: C4 C4 A3 D3
    Aeolian Mode C Minor: Bb3 Bb3 G3 C3
    Dorian Mode D Minor: G3 G3 A3 D3
    Dorian Mode E Minor: A3 A3 B3 E3
    Ionian Key of D: A3 A3 A3 D3
    Ionian Key of C: G3 G3 G3 C3
    Locrian Mode C# Minor: A3 A3 G#3 C#3
    Locrian Mode D Minor: Bb3 Bb3 A3 D3
    Lydian Mode C and More: D4 D4 G3 C3
    Lydian Mode: Bb C4 C4 F3 Bb2
    Mixolydian Mode: D4 D4 A3 D3
    Phrygian Mode: Eb4 Eb4 G3 C3
English Guittar:
    Standard: C3 E3 G3 G3 C4 C4 E4 E4 G4 G4
Gekkin:
    Standard: A3 D4 D4 D5
Ghita:
    Standard: C3 F3 C4 G4 C5
Gittern:
    Standard: D4 G4 D5 G5
Grajappi:
    Standard: F2 F2 B2 B2
Guitar:
    Standard: E2 A2 D3 G3 B3 E4
    DADGAD: D2 A2 D3 G3 A3 D4
    Double Drop D: D2 A2 D3 G3 B3 D4
    Drop D: D2 A2 D3 G3 B3 E4
    Open C: Major C2 G2 C3 G3 C3 E4
    Open D: Major D2 A2 D3 F#3 A3 D4
    Open E - 1: Major E2 B2 E3 G#3 B3 E4
    Open E - 2: Minor E2 B2 E3 G3 B3 E4
    Open G - 1: Major D2 G2 D3 G3 B3 D4
    Open G - 2: Minor D2 G2 D3 G3 Bb3 D4
    Open A: Major E2 A2 E3 A3 C#3 E4
    Renaissance: G3 G4 C4 C4 E4 E4 A4
    Baroque 1: A3 A3 D4 D4 G3 G3 B3 B3 E4 E4
    Baroque 2: A3 A3 D4 D3 G3 G3 B3 B3 E4 E4
    12-String: E2 E3 A2 A3 D3 D4 G3 G4 B3 B3 E4 E4
Guitar Banjo:
    Standard: E2 A2 D3 G3 B3 E4
Guitar Decacorde: 
    Standard: C2 D2 E2 F2 G2 A2 D3 G3 B3 E4 
Guitarra de Golpe:
    Standard: D3 G3 C4 E3 A3
Guitarro or Guitarrico:
    Standard: B4 F#4 D5 A5 E5
Guitarrón:
    Standard: A1 D2 G2 C3 E3 A2
Halszither:
    Krienser: G2 G2 D3 D3 G3 G3 B3 B3 D4 D4
Harzzither:
    Standard: G3 G3 C4 C4 E4 E4 G4 G4
Hawaiian Guitar:
    Tuning 1: E2 A2 E3 A3 C#4 E4
    Tuning 2: G2 B2 D3 G3 B3 D4
Huapanguera:
    Standard: Huapanguera
Jarana:
    Huasteca: G3 B3 D4 F#4 A4
    Jarocha: A3 D4 D4 G3 G4 B3 B3 E4
Laud:
    Standard: G#2 G#2 C#3 C#3 F#3 F#3 B3 B3 E4 E4 A4 A4
Lavta:
    Standard: C2 C2 G2 G2 D3 D3 A3 A3
Liuqin:
    Standard: G3 D4 G4 D5
Lute:
    Baroque D: Minor A2 D3 F3 A3 D4 F4
    Medieval: G2 G2 C3 C3 F3 F3 A3 A3 D4 D4 G4 G4
    Renaissance Tenor: D2 F2 G2 C3 F3 A3 D4 G4
Mandobass:
    Standard: E1 A1 D2 G2
Mandocello:
    Standard: C2 C2 G2 G2 D3 D3 A3 A3
Mandola:
    Tenor: C3 C3 G3 G3 D4 D4 A4 A4
Mandolin:
    Standard: G3 G3 D4 D4 A4 A4 E5 E5
    5 Course: C3 C3 G3 G3 D4 D4 A4 A4 E5 E5
    Electric 5-String: C3 G3 D4 A4 E5
    Cremona: G3 D4 A4 E5
    Genuese: E3 E3 A3 A3 D3 D4 G4 G4 B4 B4 E5 E5
    Neopolitan: G3 G4 D4 D4 A4 A4 E5 E5
    Piccolo: C4 C4 G4 G4 D5 D5 A5 A5
    Banjo: G3 G3 D4 D4 A5 A5 E5 E5
Mandolino:
    Standard: G3 G3 B3 B3 E4 E4 A4 A4 D5 D5 G5 G5
    Lombardo: G3 B3 E4 A4 D5 G5
Mandore:
    Modal C: C4 G4 C5 G5
    Modal G: G3 D4 G4 D5
    French: E2 A2 D3 G3 B3 E4
Mandriola or Tricordia:
    Standard:  G2 G3 G3 D3 D4 D4 A3 A4 A4 E4 E5 E5
    Unison pairs: G3 G3 G3 D4 D4 D4 A4 A4 A4 E5 E5 E5   
Mejorana:
    Standard: D4 A4 A3 B3 E4
Mondol:
    Standard: E2 E2 A2 A2 D3 D3 G3 G3 B3 B3
Octave Guitar:
    Standard: E3 A3 D4 G4 B5 E5
Panduri:
    E: E3 B3 A4
    G: G3 A3 C4
Pedal Steel Guitar:
    1: C6 C2 F2 2 C3 E3 G3 A3 C4 E4 G4
    2: E9 B2 D3 3 F#3 G#3 B3 E4 G#4 Eb4 F#4
    Universal 12 Strings: Bb2 Eb2 G2 Bb2 D3 F3 G3 Bb3 D4 F4 G4 E4
Phin:
    Standard: G4 D4 A4
Pipa:
    Standard: A2 D2 G3 A3
Portuguese Guitarra:
    Coimbra: C3 C2 G3 G2 A3 A2 D3 D3 G3 G3 A3 A3
    Lisboa: D3 D2 A3 A2 B3 B2 E3 E3 A3 A3 B3 B3
Rajão:
    Standard: D4 G4 C4 E4 A4 A4
Ramkie:
    Standard: C3 F3 A3 C4
Requinto:
   Standard: A2 D3 G3 C4 E4 A4
   4 strings - 1: G2 A2 D3 G3
   4 strings - 2: C2 D2 G2 C3
   5 Strings: E2 A2 D3 G3 C3
Ronroco:
   Standard: G3 G3 C3 C3 E4 E3 A3 A3 E4 E4
Ruan:
   Soprano: G2 D3 A3 E4
   Tenor: C2 G2 D3 A3
   Zhong: G2 D2 G3 D3
Russian Guitar:
   Standard: D2 G2 B2 D3 G3 B3 D4
Saz:
   Azeri/Qopuz: D4 D4 D4 G3 G3 C4 C4 C4
   Baglama Bozuk Duzen 6 String: G2 G3 D2 D3 A2 A3
   Baglama Bozuk Duzen 7 String: Tuning G2 G3 D2 D3 A2 A3 A3
Seis:
   Puerto Rican: F#3 F#2 B3 B2 E4 E3 A3 A3 D4 D4 G4 G4
   Puerto Rican Guitar Tuning: F#3 F#2 B3 B2 E4 E3 A3 A3 C#4 C#4 F#4 F#4
Setar:
   Standard: C3 C4 G3 C4
Sitar:
   Standard: C5 C4 G3 C2 G2 C3 F3
Soprano Guitar:
   Standard: E3 A4 D4 G4 B4 E5
Sovacon:
   Standard: G2 D3 A3 B2
Strumstick:
   Standard: G3 D4 G4
Tambur:
   Yali: D2 D2 A2 A2 D3 D3
Tamburitza:
   Brac: E2 A2 D3 G3
   Bugarija: G2 B2 D3 G3 G3
Tar:
   Standard: C3 C4 G3 G3 C4 C4
   Tar - Azeri/Caucasus: C4 C4 C5 C5 G2 C3 C4 G3 G3 C4 C4
Taro Patch:
   Standard: G3 G4 C4 C3 C4 E4 E4 A4 A4
Tenor Guitar:
   Standard: C3 G3 D4 A4
   Irish: G2 D3 A3 E3
Timple:
   Standard: G4 C5 E4 A4 D5
Tiple:
   Chilean: D4 D3 D4 G4 G3 G4 B3 B3 B3 E4 E4 E4
   Columbian: D4 D3 D4 G4 G3 G4 B3 B3 B3 E4 E4 E4
   Doliente: E3 A3 D4 G4 C5
   Martin Style: A3 A4 D4 D3 D4 F#4 F#3 F#4 B4 B4
   Requinto: D4 D4 G4 G4 G4 B4 B4 B4 E4 E4
Tres Cubano:
   C Major: G4 G3 C4 C4 E4 E3
   D Major: A4 A3 D4 D4 F#4 F#4
Tzouras:
   Standard: D3 D4 A3 A3 D4 D4
Ukulele:
   Soprano, Concert & Tenor C: C6 G4 C4 E4 A4 
   Soprano, Concert & Tenor D: D6 A4 D4 F#4 B4
   Baritone: D4 G3 B4 E4
   Tahitian: G4 G4 C5 C5 E5 E5 A4 A4
   Ukulele Banjo or Banjolele C: C6 G4 C4 E4 A4
   Ukulele Banjo or Banjolele D: D6 A4 D4 F#4 B4
Vihuela:
   Standard: A3 D4 G4 B3 E4
Viola:
   Viola Amarantina: D3 D2 A3 A2 B3 B2 E3 E3 A3 A3
   Viola Beiroa: D3 D3 A3 A2 D3 D2 G3 G2 B3 B3 D3 D3
   Viola Braguesa: C3 C2 G3 G2 A3 A2 D3 D3 G3 G3
   Viola Caipira: A3 A2 D4 D2 F#4 F#3 A3 A3 D4 D4
   Viola Campaniça: C3 C2 F3 F2 C3 C3 E3 E3 G3 G3
   Viola da Terra: A4 A4 A4 D4 D4 D3 G3 G3 B3 B3 D4 D4
   Viola de Arame: G3 G2 D3 D2 G3 G3 B3 D3 D3
   Viola de Cocho 1: G3 D3 E3 A3 D4
   Viola de Cocho 2: G3 C3 E3 A3 D4
   Viola de Diz Cordas: A3 A3 D3 D4 G3 G3 B3 B3 E4 E4
   Viola Sertaneja: A3 A2 D4 D2 F#4 F#3 A3 A3 D4 D4
   Viola Toeira: A3 A3 A3 D3 D3 D2 G3 G2 B3 B3 E3 E3
Violão de Sete Cordas:
   Standard: B1 E2 A2 D3 G3 B3 E4
Walaycho:
   Standard F: F6 C4 C4 F4 F4 A5 A4 D5 D5 A5 A5
   Standard G: G6 D4 D4 G4 G4 B5 B4 E5 E5 B5 B5
Waldzither:
   Hamburger: C3 G3 G3 C4 C4 E4 E4 G4 G4
   Thüringer: C3 G3 G3 C4 C4 E4 E4 G4 G4
Yueh Chin or Yueh Qin:
   Standard: G3 D4 G4 D5
Zister:
   Thüringer: C3 G3 G3 C4 C4 E4 E4 G4 G4

# Instruments with 13 or more strings
Angelique (Theorbo):
   Standard: D2 E2 F2 G2 A2 B2 C3 D3 E3 F3 G3 A3 B3 C4 D4 E4
Archlute: 
   14 Course: F2 G2 A2 Bb2 C3 D3 E3 F3 G3 C4 F4 A4 D5 G5
Bandolin:
   Ecuadorean: E5 E4 E5 A5 A4 A5 D5 D4 D5 F5 F5 F5 B5 B5 B5
Baroque Lute:
   Standard: A2 B2 C3 D3 E3 F3 G3 A3 D4 F4 A4 D5 F5
Guitarrón Chileno:
   Standard: F#5 A4 D4 D4 D3 D3 D2 G4 G4 G4 G3 G3 C4 C4 C3 C2 E4 E4 E4 A4 A4 A4 G4 B4
Laud - Phillipines:
   Standard: F#2 B2 B2 E3 E3 A3 A3 A3 D4 D4 D4 G4 G4 G4
Liuto Attiorbato (Theorbo):
   Standard: F1 F2 G1 G2 A1 A2 B1 B2 C2 C3 D2 D3 E2 E3 F2 F2 G2 G2 C3 C3 F3 F3 A3 A3 D4 D4 G4
Octavina:
   Standard: F#2 B2 B2 E3 E3 A3 A3 A3 D4 D4 D4 G4 G4 G4
Sächsische Theorbenzister:
   Standard: B2 C2 D3 E3 F3 G3 A3 B3 C4 C4 F4 F4 A4 A4 C4 C4
Swedish Lute:
   Standard: A2 B2 C#3 D3 E3 F#3 G3 A3 B3 C#4 D4 E4 A4 C#5 E5
Theorbo - 15 Course:
   Standard: F2 G2 A2 B2 C3 D3 E3 F3 G3 A3 D4 G4 B4 E4 A4
Viola da Terceira - 15 String:
   Standard: E3 E3 E2 A3 A3 A2 D3 D3 D2 G3 G2 B3 B3 E3 E3
