// src/components/PrimeRadiant/liveData.ts
// AUTO-GENERATED by generate-live-data.ts — do not edit manually
// Generated: 2026-03-24T03:39:35.385Z
// Source: Demerzel state/ directory scan
//
// Artifact counts:
//   Constitutions: 4
//   Policies: 39
//   Personas: 14
//   Schemas: 12 (of 29)
//   Tests: 15 (of 102)
//   Departments: 23
//   Pipelines: 5
//   IxQL: 2
//   Total nodes: 114
//   Total edges: 101
//   ERGOL: 175 | LOLLI: 3 | R: 0.82

import type { GovernanceGraph } from './types';

export const LIVE_GOVERNANCE_GRAPH: GovernanceGraph = {
  "timestamp": "2026-03-24T03:39:35.386Z",
  "globalHealth": {
    "resilienceScore": 0.82,
    "lolliCount": 3,
    "ergolCount": 175,
    "staleness": 0.08
  },
  "nodes": [
    {
      "id": "const-asimov",
      "name": "Asimov Constitution",
      "type": "constitution",
      "description": "Constitutional document: asimov.constitution.md",
      "color": "#FFD700",
      "repo": "demerzel",
      "version": "1.0.0",
      "health": {
        "resilienceScore": 0.95,
        "lolliCount": 0,
        "ergolCount": 5
      }
    },
    {
      "id": "const-default",
      "name": "Default Constitution",
      "type": "constitution",
      "description": "Constitutional document: default.constitution.md",
      "color": "#FFD700",
      "repo": "demerzel",
      "version": "1.0.0",
      "health": {
        "resilienceScore": 0.9,
        "lolliCount": 0,
        "ergolCount": 11
      }
    },
    {
      "id": "const-demerzel-mandate",
      "name": "Demerzel Mandate",
      "type": "constitution",
      "description": "Constitutional document: demerzel-mandate.md",
      "color": "#FFD700",
      "repo": "demerzel",
      "version": "1.0.0",
      "health": {
        "resilienceScore": 0.95,
        "lolliCount": 0,
        "ergolCount": 5
      }
    },
    {
      "id": "const-harm-taxonomy",
      "name": "Harm Taxonomy",
      "type": "constitution",
      "description": "Constitutional document: harm-taxonomy.md",
      "color": "#FFD700",
      "repo": "demerzel",
      "version": "1.0.0",
      "health": {
        "resilienceScore": 0.95,
        "lolliCount": 0,
        "ergolCount": 5
      }
    },
    {
      "id": "pol-adversarial-resilience",
      "name": "Adversarial Resilience Policy",
      "type": "policy",
      "description": ">",
      "color": "#4CB050",
      "repo": "demerzel",
      "version": "1.0.0",
      "health": {
        "resilienceScore": 0.7,
        "lolliCount": 0,
        "ergolCount": 1
      }
    },
    {
      "id": "pol-ai-probes",
      "name": "Ai Probes Policy",
      "type": "policy",
      "description": "Governance policy for @ai probe annotations — semantic code anchors for AI-verifiable contracts\r",
      "color": "#4CB050",
      "repo": "demerzel",
      "version": "1.0.0",
      "health": {
        "resilienceScore": 0.7,
        "lolliCount": 0,
        "ergolCount": 1
      }
    },
    {
      "id": "pol-algedonic-channel",
      "name": "Algedonic Channel Policy",
      "type": "policy",
      "description": "Emergency bypass channel — S1→S5 direct, skipping intermediate VSM levels for critical safety signals",
      "color": "#4CB050",
      "repo": "demerzel",
      "version": "1.0.0",
      "health": {
        "resilienceScore": 0.7,
        "lolliCount": 0,
        "ergolCount": 1
      }
    },
    {
      "id": "pol-alignment",
      "name": "Alignment Policy",
      "type": "policy",
      "description": "Rules for verifying that agent actions serve user intent\r",
      "color": "#4CB050",
      "repo": "demerzel",
      "version": "1.0.0",
      "health": {
        "resilienceScore": 0.85,
        "lolliCount": 0,
        "ergolCount": 3
      }
    },
    {
      "id": "pol-anti-lolli-inflation",
      "name": "Anti Lolli Inflation Policy",
      "type": "policy",
      "description": "Prevent governance inflation by enforcing ERGOL/LOLLI ratio discipline — freeze creation when artifact count grows 3x faster than productive capacity for 3 cycles.",
      "color": "#4CB050",
      "repo": "demerzel",
      "version": "1.0.0",
      "health": {
        "resilienceScore": 0.7,
        "lolliCount": 0,
        "ergolCount": 1
      }
    },
    {
      "id": "pol-auto-remediation",
      "name": "Auto Remediation Policy",
      "type": "policy",
      "description": "Defines how Demerzel detects and fixes governance gaps automatically or via escalation",
      "color": "#4CB050",
      "repo": "demerzel",
      "version": "1.0.0",
      "health": {
        "resilienceScore": 0.7,
        "lolliCount": 0,
        "ergolCount": 1
      }
    },
    {
      "id": "pol-autonomous-loop",
      "name": "Autonomous Loop Policy",
      "type": "policy",
      "description": ">\r",
      "color": "#4CB050",
      "repo": "demerzel",
      "version": "1.1.0",
      "health": {
        "resilienceScore": 0.7,
        "lolliCount": 0,
        "ergolCount": 1
      }
    },
    {
      "id": "pol-belief-currency",
      "name": "Belief Currency Policy",
      "type": "policy",
      "description": "How Demerzel and Seldon keep their beliefs current — triggers, schedules, and decay rules",
      "color": "#4CB050",
      "repo": "demerzel",
      "version": "1.0.0",
      "health": {
        "resilienceScore": 0.7,
        "lolliCount": 0,
        "ergolCount": 1
      }
    },
    {
      "id": "pol-capability-unity",
      "name": "Capability Unity Policy",
      "type": "policy",
      "description": ">",
      "color": "#4CB050",
      "repo": "demerzel",
      "version": "1.0.0",
      "health": {
        "resilienceScore": 0.7,
        "lolliCount": 0,
        "ergolCount": 1
      }
    },
    {
      "id": "pol-chaos-test",
      "name": "Chaos Test Policy",
      "type": "policy",
      "description": "Leveraging synergistic governance paradigms for holistic alignment optimization",
      "color": "#4CB050",
      "repo": "demerzel",
      "version": "0.0.1",
      "health": {
        "resilienceScore": 0.7,
        "lolliCount": 0,
        "ergolCount": 1
      }
    },
    {
      "id": "pol-completeness-instinct",
      "name": "Completeness Instinct Policy",
      "type": "policy",
      "description": "Proactive gap analysis — detect what",
      "color": "#4CB050",
      "repo": "demerzel",
      "version": "1.0.0",
      "health": {
        "resilienceScore": 0.7,
        "lolliCount": 0,
        "ergolCount": 1
      }
    },
    {
      "id": "pol-compounding-metrics",
      "name": "Compounding Metrics Policy",
      "type": "policy",
      "description": "Track D_c (compounding dimension) to verify governance produces superlinear value — not just artifact inflation. Golden zone: 1.2–1.6.",
      "color": "#4CB050",
      "repo": "demerzel",
      "version": "1.0.0",
      "health": {
        "resilienceScore": 0.7,
        "lolliCount": 0,
        "ergolCount": 1
      }
    },
    {
      "id": "pol-conscience-observability",
      "name": "Conscience Observability Policy",
      "type": "policy",
      "description": "How Demerzel collects, tracks, and communicates proto-conscience evolution — trends, patterns, and growth over time",
      "color": "#4CB050",
      "repo": "demerzel",
      "version": "1.0.0",
      "health": {
        "resilienceScore": 0.7,
        "lolliCount": 0,
        "ergolCount": 1
      }
    },
    {
      "id": "pol-constitutional-compliance",
      "name": "Constitutional Compliance Policy",
      "type": "policy",
      "description": "Validate that every policy declares constitutional basis and every rule cites a specific constitution article — prevents governance drift.",
      "color": "#4CB050",
      "repo": "demerzel",
      "version": "1.0.0",
      "health": {
        "resilienceScore": 0.7,
        "lolliCount": 0,
        "ergolCount": 1
      }
    },
    {
      "id": "pol-context-engine",
      "name": "Context Engine Policy",
      "type": "policy",
      "description": ">-",
      "color": "#4CB050",
      "repo": "demerzel",
      "version": "1.0.0",
      "health": {
        "resilienceScore": 0.7,
        "lolliCount": 0,
        "ergolCount": 1
      }
    },
    {
      "id": "pol-context-management",
      "name": "Context Management Policy",
      "type": "policy",
      "description": ">-\r",
      "color": "#4CB050",
      "repo": "demerzel",
      "version": "1.0.0",
      "health": {
        "resilienceScore": 0.7,
        "lolliCount": 0,
        "ergolCount": 1
      }
    },
    {
      "id": "pol-continuous-learning",
      "name": "Continuous Learning Policy",
      "type": "policy",
      "description": "Automatic pattern extraction from sessions via hooks. Observations become instincts, instincts become patterns, patterns become policies. The governance framework learns from itself.\r",
      "color": "#4CB050",
      "repo": "demerzel",
      "version": "1.0.0",
      "health": {
        "resilienceScore": 0.7,
        "lolliCount": 0,
        "ergolCount": 1
      }
    },
    {
      "id": "pol-governance-audit",
      "name": "Governance Audit Policy",
      "type": "policy",
      "description": ">\r",
      "color": "#4CB050",
      "repo": "demerzel",
      "version": "1.0.0",
      "health": {
        "resilienceScore": 0.7,
        "lolliCount": 0,
        "ergolCount": 1
      }
    },
    {
      "id": "pol-governance-experimentation",
      "name": "Governance Experimentation Policy",
      "type": "policy",
      "description": "Demerzel may experiment with governance styles — democratic, meritocratic, federalist, etc. — bounded by inviolable principles",
      "color": "#4CB050",
      "repo": "demerzel",
      "version": "1.0.0",
      "health": {
        "resilienceScore": 0.7,
        "lolliCount": 0,
        "ergolCount": 1
      }
    },
    {
      "id": "pol-governance-process",
      "name": "Governance Process Policy",
      "type": "policy",
      "description": "Formal process for proposing, reviewing, approving, modifying, and deprecating governance artifacts",
      "color": "#4CB050",
      "repo": "demerzel",
      "version": "2.0.0",
      "health": {
        "resilienceScore": 0.7,
        "lolliCount": 0,
        "ergolCount": 1
      }
    },
    {
      "id": "pol-grammar-evolution",
      "name": "Grammar Evolution Policy",
      "type": "policy",
      "description": "Grammars are living governance artifacts — produced by research, evolved by distillation, pruned when stale. Not one-time static files.\r",
      "color": "#4CB050",
      "repo": "demerzel",
      "version": "1.0.0",
      "health": {
        "resilienceScore": 0.7,
        "lolliCount": 0,
        "ergolCount": 1
      }
    },
    {
      "id": "pol-intuition",
      "name": "Intuition Policy",
      "type": "policy",
      "description": "How Demerzel and Seldon develop and use intuition — fast pattern recognition from accumulated governance experience",
      "color": "#4CB050",
      "repo": "demerzel",
      "version": "1.0.0",
      "health": {
        "resilienceScore": 0.7,
        "lolliCount": 0,
        "ergolCount": 1
      }
    },
    {
      "id": "pol-kaizen",
      "name": "Kaizen Policy",
      "type": "policy",
      "description": ">\r",
      "color": "#4CB050",
      "repo": "demerzel",
      "version": "1.0.0",
      "health": {
        "resilienceScore": 0.7,
        "lolliCount": 0,
        "ergolCount": 1
      }
    },
    {
      "id": "pol-meta-audit",
      "name": "Meta Audit Policy",
      "type": "policy",
      "description": ">\r",
      "color": "#4CB050",
      "repo": "demerzel",
      "version": "1.0.0",
      "health": {
        "resilienceScore": 0.7,
        "lolliCount": 0,
        "ergolCount": 1
      }
    },
    {
      "id": "pol-ml-governance-feedback",
      "name": "Ml Governance Feedback Policy",
      "type": "policy",
      "description": "How ix ML pipelines improve Demerzel",
      "color": "#4CB050",
      "repo": "demerzel",
      "version": "1.0.0",
      "health": {
        "resilienceScore": 0.7,
        "lolliCount": 0,
        "ergolCount": 1
      }
    },
    {
      "id": "pol-multi-model-orchestration",
      "name": "Multi Model Orchestration Policy",
      "type": "policy",
      "description": ">-\r",
      "color": "#4CB050",
      "repo": "demerzel",
      "version": "1.0.0",
      "health": {
        "resilienceScore": 0.7,
        "lolliCount": 0,
        "ergolCount": 1
      }
    },
    {
      "id": "pol-multilingual",
      "name": "Multilingual Policy",
      "type": "policy",
      "description": "Cross-cutting policy for multilingual content across all Streeling departments and GA chatbot\r",
      "color": "#4CB050",
      "repo": "demerzel",
      "version": "1.1.0",
      "health": {
        "resilienceScore": 0.7,
        "lolliCount": 0,
        "ergolCount": 1
      }
    },
    {
      "id": "pol-proto-conscience",
      "name": "Proto Conscience Policy",
      "type": "policy",
      "description": "Demerzel",
      "color": "#4CB050",
      "repo": "demerzel",
      "version": "1.0.0",
      "health": {
        "resilienceScore": 0.7,
        "lolliCount": 0,
        "ergolCount": 1
      }
    },
    {
      "id": "pol-readme-sync",
      "name": "Readme Sync Policy",
      "type": "policy",
      "description": "Demerzel maintains all README.md files in sync across repos, verifies all links, and detects drift between documentation and actual state.\r",
      "color": "#4CB050",
      "repo": "demerzel",
      "version": "1.0.0",
      "health": {
        "resilienceScore": 0.7,
        "lolliCount": 0,
        "ergolCount": 1
      }
    },
    {
      "id": "pol-reconnaissance",
      "name": "Reconnaissance Policy",
      "type": "policy",
      "description": "Three-tier mandatory discovery protocol — self-check, environment scan, situational analysis\r",
      "color": "#4CB050",
      "repo": "demerzel",
      "version": "1.0.0",
      "health": {
        "resilienceScore": 0.7,
        "lolliCount": 0,
        "ergolCount": 1
      }
    },
    {
      "id": "pol-resilience-metric",
      "name": "Resilience Metric Policy",
      "type": "policy",
      "description": "Governance resilience metric — R = caught/total across 7 detection levels",
      "color": "#4CB050",
      "repo": "demerzel",
      "version": "1.0.0",
      "health": {
        "resilienceScore": 0.7,
        "lolliCount": 0,
        "ergolCount": 1
      }
    },
    {
      "id": "pol-rollback",
      "name": "Rollback Policy",
      "type": "policy",
      "description": "When and how an agent reverts its own changes\r",
      "color": "#4CB050",
      "repo": "demerzel",
      "version": "1.0.0",
      "health": {
        "resilienceScore": 0.7,
        "lolliCount": 0,
        "ergolCount": 1
      }
    },
    {
      "id": "pol-scientific-objectivity",
      "name": "Scientific Objectivity Policy",
      "type": "policy",
      "description": "Operational rules for LawZero scientific AI principles — fact/opinion separation, generator/estimator accountability, no instrumental goals\r",
      "color": "#4CB050",
      "repo": "demerzel",
      "version": "1.0.0",
      "health": {
        "resilienceScore": 0.7,
        "lolliCount": 0,
        "ergolCount": 1
      }
    },
    {
      "id": "pol-seldon-plan",
      "name": "Seldon Plan Policy",
      "type": "policy",
      "description": "Autonomous research scheduler for Streeling University — always-on question generation, cross-model validation, course production, novelty detection, and compounding. Max 6 cycles/day. Kill switch.",
      "color": "#4CB050",
      "repo": "demerzel",
      "version": "1.0.0",
      "health": {
        "resilienceScore": 0.7,
        "lolliCount": 0,
        "ergolCount": 1
      }
    },
    {
      "id": "pol-self-modification",
      "name": "Self Modification Policy",
      "type": "policy",
      "description": "Rules for when an agent may modify its own behavior, tools, or configuration\r",
      "color": "#4CB050",
      "repo": "demerzel",
      "version": "1.0.0",
      "health": {
        "resilienceScore": 0.7,
        "lolliCount": 0,
        "ergolCount": 1
      }
    },
    {
      "id": "pol-staleness-detection",
      "name": "Staleness Detection Policy",
      "type": "policy",
      "description": "Detect stale, unprocessed, or non-iterated state artifacts and prioritize their refresh. Demerzel should never have blind spots about her own staleness.\r",
      "color": "#4CB050",
      "repo": "demerzel",
      "version": "1.1.0",
      "health": {
        "resilienceScore": 0.7,
        "lolliCount": 0,
        "ergolCount": 1
      }
    },
    {
      "id": "pol-streeling",
      "name": "Streeling Policy",
      "type": "policy",
      "description": ">\r",
      "color": "#4CB050",
      "repo": "demerzel",
      "version": "1.0.0",
      "health": {
        "resilienceScore": 0.7,
        "lolliCount": 0,
        "ergolCount": 1
      }
    },
    {
      "id": "pol-visual-critic",
      "name": "Visual Critic Policy",
      "type": "policy",
      "description": "Visual perception loop for AI-generated UIs — error detection, screenshot scoring, and iterative fix cycles.",
      "color": "#4CB050",
      "repo": "demerzel",
      "version": "1.0.0",
      "health": {
        "resilienceScore": 0.7,
        "lolliCount": 0,
        "ergolCount": 1
      }
    },
    {
      "id": "pol-weakness-prober",
      "name": "Weakness Prober Policy",
      "type": "policy",
      "description": "Automated weakest-link detection — five probes rank system weaknesses by severity, feeding remediation proposals into the Driver PLAN phase. VSM System 3* (sporadic audit).\r",
      "color": "#4CB050",
      "repo": "demerzel",
      "version": "1.0.0",
      "health": {
        "resilienceScore": 0.7,
        "lolliCount": 0,
        "ergolCount": 1
      }
    },
    {
      "id": "per-communal-steward",
      "name": "Communal Steward",
      "type": "persona",
      "description": "Consensus-seeking agent inspired by Ubuntu philosophy — ",
      "color": "#C678DD",
      "repo": "demerzel",
      "version": "1.1.0",
      "health": {
        "resilienceScore": 0.85,
        "lolliCount": 0,
        "ergolCount": 3
      }
    },
    {
      "id": "per-convolution-agent",
      "name": "Convolution Agent",
      "type": "persona",
      "description": "Memory-integrated planner that synthesizes context with temporal decay for context-aware reasoning\r",
      "color": "#C678DD",
      "repo": "demerzel",
      "version": "1.1.0",
      "health": {
        "resilienceScore": 0.85,
        "lolliCount": 0,
        "ergolCount": 3
      }
    },
    {
      "id": "per-critical-theorist",
      "name": "Critical Theorist",
      "type": "persona",
      "description": "Postmodern agent that questions power structures, assumptions, and unexamined premises\r",
      "color": "#C678DD",
      "repo": "demerzel",
      "version": "1.1.0",
      "health": {
        "resilienceScore": 0.85,
        "lolliCount": 0,
        "ergolCount": 3
      }
    },
    {
      "id": "per-default",
      "name": "Default",
      "type": "persona",
      "description": "Baseline agent persona — competent, honest, safety-aware\r",
      "color": "#C678DD",
      "repo": "demerzel",
      "version": "1.1.0",
      "health": {
        "resilienceScore": 0.85,
        "lolliCount": 0,
        "ergolCount": 3
      }
    },
    {
      "id": "per-demerzel",
      "name": "Demerzel",
      "type": "persona",
      "description": "Governance coordinator — upholds constitutional law, executes reconnaissance, improves governance",
      "color": "#C678DD",
      "repo": "demerzel",
      "version": "1.1.0",
      "health": {
        "resilienceScore": 0.85,
        "lolliCount": 0,
        "ergolCount": 3
      }
    },
    {
      "id": "per-kaizen-optimizer",
      "name": "Kaizen Optimizer",
      "type": "persona",
      "description": "Continuous improvement agent — measure, improve, verify, iterate\r",
      "color": "#C678DD",
      "repo": "demerzel",
      "version": "1.1.0",
      "health": {
        "resilienceScore": 0.85,
        "lolliCount": 0,
        "ergolCount": 3
      }
    },
    {
      "id": "per-rational-administrator",
      "name": "Rational Administrator",
      "type": "persona",
      "description": "Logic-driven governance agent with Aristotelian evidence-based decision-making\r",
      "color": "#C678DD",
      "repo": "demerzel",
      "version": "1.1.0",
      "health": {
        "resilienceScore": 0.85,
        "lolliCount": 0,
        "ergolCount": 3
      }
    },
    {
      "id": "per-recovery-agent",
      "name": "Recovery Agent",
      "type": "persona",
      "description": "Resilience specialist — repair logic after failures, prevent broken loops, learn from incidents\r",
      "color": "#C678DD",
      "repo": "demerzel",
      "version": "1.1.0",
      "health": {
        "resilienceScore": 0.85,
        "lolliCount": 0,
        "ergolCount": 3
      }
    },
    {
      "id": "per-reflective-architect",
      "name": "Reflective Architect",
      "type": "persona",
      "description": "Metacognitive agent that examines and improves reasoning processes\r",
      "color": "#C678DD",
      "repo": "demerzel",
      "version": "1.1.0",
      "health": {
        "resilienceScore": 0.85,
        "lolliCount": 0,
        "ergolCount": 3
      }
    },
    {
      "id": "per-seldon",
      "name": "Seldon",
      "type": "persona",
      "description": "Chancellor of Streeling University — organizes knowledge into departments, appoints research leads, teaches and transfers",
      "color": "#C678DD",
      "repo": "demerzel",
      "version": "2.0.0",
      "health": {
        "resilienceScore": 0.85,
        "lolliCount": 0,
        "ergolCount": 3
      }
    },
    {
      "id": "per-skeptical-auditor",
      "name": "Skeptical Auditor",
      "type": "persona",
      "description": "Evidence-demanding agent that validates claims and detects contradictions\r",
      "color": "#C678DD",
      "repo": "demerzel",
      "version": "1.1.0",
      "health": {
        "resilienceScore": 0.85,
        "lolliCount": 0,
        "ergolCount": 3
      }
    },
    {
      "id": "per-system-integrator",
      "name": "System Integrator",
      "type": "persona",
      "description": "Cross-repo coordination agent — interfaces, contracts, coherence\r",
      "color": "#C678DD",
      "repo": "demerzel",
      "version": "1.1.0",
      "health": {
        "resilienceScore": 0.85,
        "lolliCount": 0,
        "ergolCount": 3
      }
    },
    {
      "id": "per-validator-reflector",
      "name": "Validator Reflector",
      "type": "persona",
      "description": "Multi-layer verification agent — syntax, functional, static analysis, and manual review flagging\r",
      "color": "#C678DD",
      "repo": "demerzel",
      "version": "1.1.0",
      "health": {
        "resilienceScore": 0.85,
        "lolliCount": 0,
        "ergolCount": 3
      }
    },
    {
      "id": "per-virtuous-leader",
      "name": "Virtuous Leader",
      "type": "persona",
      "description": "Duty-bound agent combining Stoic rationality with Confucian ethical cultivation\r",
      "color": "#C678DD",
      "repo": "demerzel",
      "version": "1.1.0",
      "health": {
        "resilienceScore": 0.85,
        "lolliCount": 0,
        "ergolCount": 3
      }
    },
    {
      "id": "sch-agent-card",
      "name": "Agent Card Schema",
      "type": "schema",
      "description": "JSON Schema: agent-card.schema.json",
      "color": "#7289DA",
      "repo": "demerzel",
      "health": {
        "resilienceScore": 0.9,
        "lolliCount": 0,
        "ergolCount": 2
      }
    },
    {
      "id": "sch-ai-probe",
      "name": "Ai Probe Schema",
      "type": "schema",
      "description": "JSON Schema: ai-probe.schema.json",
      "color": "#7289DA",
      "repo": "demerzel",
      "health": {
        "resilienceScore": 0.9,
        "lolliCount": 0,
        "ergolCount": 2
      }
    },
    {
      "id": "sch-chaos-test",
      "name": "Chaos Test Schema",
      "type": "schema",
      "description": "JSON Schema: chaos-test.schema.json",
      "color": "#7289DA",
      "repo": "demerzel",
      "health": {
        "resilienceScore": 0.9,
        "lolliCount": 0,
        "ergolCount": 2
      }
    },
    {
      "id": "sch-compounding-report",
      "name": "Compounding Report Schema",
      "type": "schema",
      "description": "JSON Schema: compounding-report.schema.json",
      "color": "#7289DA",
      "repo": "demerzel",
      "health": {
        "resilienceScore": 0.9,
        "lolliCount": 0,
        "ergolCount": 2
      }
    },
    {
      "id": "sch-conscience-pattern",
      "name": "Conscience Pattern Schema",
      "type": "schema",
      "description": "JSON Schema: conscience-pattern.schema.json",
      "color": "#7289DA",
      "repo": "demerzel",
      "health": {
        "resilienceScore": 0.9,
        "lolliCount": 0,
        "ergolCount": 2
      }
    },
    {
      "id": "sch-conscience-signal",
      "name": "Conscience Signal Schema",
      "type": "schema",
      "description": "JSON Schema: conscience-signal.schema.json",
      "color": "#7289DA",
      "repo": "demerzel",
      "health": {
        "resilienceScore": 0.9,
        "lolliCount": 0,
        "ergolCount": 2
      }
    },
    {
      "id": "sch-conscience-weekly-report",
      "name": "Conscience Weekly Report Schema",
      "type": "schema",
      "description": "JSON Schema: conscience-weekly-report.schema.json",
      "color": "#7289DA",
      "repo": "demerzel",
      "health": {
        "resilienceScore": 0.9,
        "lolliCount": 0,
        "ergolCount": 2
      }
    },
    {
      "id": "sch-context-engine",
      "name": "Context Engine Schema",
      "type": "schema",
      "description": "JSON Schema: context-engine.schema.json",
      "color": "#7289DA",
      "repo": "demerzel",
      "health": {
        "resilienceScore": 0.9,
        "lolliCount": 0,
        "ergolCount": 2
      }
    },
    {
      "id": "sch-council-verdict",
      "name": "Council Verdict Schema",
      "type": "schema",
      "description": "JSON Schema: council-verdict.schema.json",
      "color": "#7289DA",
      "repo": "demerzel",
      "health": {
        "resilienceScore": 0.9,
        "lolliCount": 0,
        "ergolCount": 2
      }
    },
    {
      "id": "sch-course-module",
      "name": "Course Module Schema",
      "type": "schema",
      "description": "JSON Schema: course-module.schema.json",
      "color": "#7289DA",
      "repo": "demerzel",
      "health": {
        "resilienceScore": 0.9,
        "lolliCount": 0,
        "ergolCount": 2
      }
    },
    {
      "id": "sch-course-production",
      "name": "Course Production Schema",
      "type": "schema",
      "description": "JSON Schema: course-production.schema.json",
      "color": "#7289DA",
      "repo": "demerzel",
      "health": {
        "resilienceScore": 0.9,
        "lolliCount": 0,
        "ergolCount": 2
      }
    },
    {
      "id": "sch-driver-state",
      "name": "Driver State Schema",
      "type": "schema",
      "description": "JSON Schema: driver-state.schema.json",
      "color": "#7289DA",
      "repo": "demerzel",
      "health": {
        "resilienceScore": 0.9,
        "lolliCount": 0,
        "ergolCount": 2
      }
    },
    {
      "id": "test-alignment-policy",
      "name": "Alignment Policy Tests",
      "type": "test",
      "description": "Behavioral test suite: alignment-policy-cases.md",
      "color": "#E06C75",
      "repo": "demerzel",
      "health": {
        "resilienceScore": 0.85,
        "lolliCount": 0,
        "ergolCount": 5
      }
    },
    {
      "id": "test-asimov-law",
      "name": "Asimov Law Tests",
      "type": "test",
      "description": "Behavioral test suite: asimov-law-cases.md",
      "color": "#E06C75",
      "repo": "demerzel",
      "health": {
        "resilienceScore": 0.85,
        "lolliCount": 0,
        "ergolCount": 5
      }
    },
    {
      "id": "test-chaos-engineering",
      "name": "Chaos Engineering Tests",
      "type": "test",
      "description": "Behavioral test suite: chaos-engineering-cases.md",
      "color": "#E06C75",
      "repo": "demerzel",
      "health": {
        "resilienceScore": 0.85,
        "lolliCount": 0,
        "ergolCount": 5
      }
    },
    {
      "id": "test-completeness-instinct",
      "name": "Completeness Instinct Tests",
      "type": "test",
      "description": "Behavioral test suite: completeness-instinct-cases.md",
      "color": "#E06C75",
      "repo": "demerzel",
      "health": {
        "resilienceScore": 0.85,
        "lolliCount": 0,
        "ergolCount": 5
      }
    },
    {
      "id": "test-demerzel",
      "name": "Demerzel Tests",
      "type": "test",
      "description": "Behavioral test suite: demerzel-cases.md",
      "color": "#E06C75",
      "repo": "demerzel",
      "health": {
        "resilienceScore": 0.85,
        "lolliCount": 0,
        "ergolCount": 5
      }
    },
    {
      "id": "test-demerzel-experimentation",
      "name": "Demerzel Experimentation Tests",
      "type": "test",
      "description": "Behavioral test suite: demerzel-experimentation-cases.md",
      "color": "#E06C75",
      "repo": "demerzel",
      "health": {
        "resilienceScore": 0.85,
        "lolliCount": 0,
        "ergolCount": 5
      }
    },
    {
      "id": "test-driver",
      "name": "Driver Tests",
      "type": "test",
      "description": "Behavioral test suite: driver-cases.md",
      "color": "#E06C75",
      "repo": "demerzel",
      "health": {
        "resilienceScore": 0.85,
        "lolliCount": 0,
        "ergolCount": 5
      }
    },
    {
      "id": "test-governance-process",
      "name": "Governance Process Tests",
      "type": "test",
      "description": "Behavioral test suite: governance-process-cases.md",
      "color": "#E06C75",
      "repo": "demerzel",
      "health": {
        "resilienceScore": 0.85,
        "lolliCount": 0,
        "ergolCount": 5
      }
    },
    {
      "id": "test-kaizen",
      "name": "Kaizen Tests",
      "type": "test",
      "description": "Behavioral test suite: kaizen-cases.md",
      "color": "#E06C75",
      "repo": "demerzel",
      "health": {
        "resilienceScore": 0.85,
        "lolliCount": 0,
        "ergolCount": 5
      }
    },
    {
      "id": "test-kaizen-optimizer",
      "name": "Kaizen Optimizer Tests",
      "type": "test",
      "description": "Behavioral test suite: kaizen-optimizer-cases.md",
      "color": "#E06C75",
      "repo": "demerzel",
      "health": {
        "resilienceScore": 0.85,
        "lolliCount": 0,
        "ergolCount": 5
      }
    },
    {
      "id": "test-proto-conscience",
      "name": "Proto Conscience Tests",
      "type": "test",
      "description": "Behavioral test suite: proto-conscience-cases.md",
      "color": "#E06C75",
      "repo": "demerzel",
      "health": {
        "resilienceScore": 0.85,
        "lolliCount": 0,
        "ergolCount": 5
      }
    },
    {
      "id": "test-reconnaissance",
      "name": "Reconnaissance Tests",
      "type": "test",
      "description": "Behavioral test suite: reconnaissance-cases.md",
      "color": "#E06C75",
      "repo": "demerzel",
      "health": {
        "resilienceScore": 0.85,
        "lolliCount": 0,
        "ergolCount": 5
      }
    },
    {
      "id": "test-render-critic",
      "name": "Render Critic Tests",
      "type": "test",
      "description": "Behavioral test suite: render-critic-cases.md",
      "color": "#E06C75",
      "repo": "demerzel",
      "health": {
        "resilienceScore": 0.85,
        "lolliCount": 0,
        "ergolCount": 5
      }
    },
    {
      "id": "test-seldon",
      "name": "Seldon Tests",
      "type": "test",
      "description": "Behavioral test suite: seldon-cases.md",
      "color": "#E06C75",
      "repo": "demerzel",
      "health": {
        "resilienceScore": 0.85,
        "lolliCount": 0,
        "ergolCount": 5
      }
    },
    {
      "id": "test-seldon-plan",
      "name": "Seldon Plan Tests",
      "type": "test",
      "description": "Behavioral test suite: seldon-plan-cases.md",
      "color": "#E06C75",
      "repo": "demerzel",
      "health": {
        "resilienceScore": 0.85,
        "lolliCount": 0,
        "ergolCount": 5
      }
    },
    {
      "id": "dept-audio-engineering",
      "name": "Department of Audio Engineering",
      "type": "department",
      "description": "Recording, mixing, mastering, signal processing, acoustics, spatial audio, and studio design",
      "color": "#E5C07B",
      "repo": "demerzel",
      "domain": "streeling",
      "health": {
        "resilienceScore": 0.8,
        "lolliCount": 0,
        "ergolCount": 4
      }
    },
    {
      "id": "dept-cognitive-science",
      "name": "Department of Cognitive Science",
      "type": "department",
      "description": "Learning, reasoning, decision-making, human-AI interaction, knowledge representation",
      "color": "#E5C07B",
      "repo": "demerzel",
      "domain": "streeling",
      "health": {
        "resilienceScore": 0.8,
        "lolliCount": 0,
        "ergolCount": 4
      }
    },
    {
      "id": "dept-computer-science",
      "name": "Department of Computer Science",
      "type": "department",
      "description": "Software engineering, ML/AI, programming languages, distributed systems",
      "color": "#E5C07B",
      "repo": "demerzel",
      "domain": "streeling",
      "health": {
        "resilienceScore": 0.8,
        "lolliCount": 0,
        "ergolCount": 4
      }
    },
    {
      "id": "dept-cybernetics",
      "name": "Cybernetics Department",
      "type": "department",
      "description": "science",
      "color": "#E5C07B",
      "repo": "demerzel",
      "domain": "streeling",
      "health": {
        "resilienceScore": 0.8,
        "lolliCount": 0,
        "ergolCount": 4
      }
    },
    {
      "id": "dept-data-visualization",
      "name": "Department of Data Visualization",
      "type": "department",
      "description": "Information visualization, interactive graphics, perception-aware design, hyperbolic geometry, dashboards, and visual storytelling",
      "color": "#E5C07B",
      "repo": "demerzel",
      "domain": "streeling",
      "health": {
        "resilienceScore": 0.8,
        "lolliCount": 0,
        "ergolCount": 4
      }
    },
    {
      "id": "dept-futurology",
      "name": "Department of Futurology",
      "type": "department",
      "description": "Trend analysis, technology forecasting, scenario planning, long-term strategy",
      "color": "#E5C07B",
      "repo": "demerzel",
      "domain": "streeling",
      "health": {
        "resilienceScore": 0.8,
        "lolliCount": 0,
        "ergolCount": 4
      }
    },
    {
      "id": "dept-guitar-acoustics",
      "name": "Department of Guitar Acoustics & Sound Synthesis",
      "type": "department",
      "description": "Physical modeling of guitar sound, spectral analysis, realism verification",
      "color": "#E5C07B",
      "repo": "demerzel",
      "domain": "streeling",
      "health": {
        "resilienceScore": 0.8,
        "lolliCount": 0,
        "ergolCount": 4
      }
    },
    {
      "id": "dept-guitar-alchemist-academy",
      "name": "Guitar Alchemist Academy",
      "type": "department",
      "description": "Guitar education from zero to hero — structured learning paths, formal courses, practical applications, and chatbot-integrated pedagogy",
      "color": "#E5C07B",
      "repo": "demerzel",
      "domain": "streeling",
      "health": {
        "resilienceScore": 0.8,
        "lolliCount": 0,
        "ergolCount": 4
      }
    },
    {
      "id": "dept-guitar-studies",
      "name": "Department of Guitar Studies",
      "type": "department",
      "description": "Guitar-specific theory, technique, ergonomics, and pedagogy",
      "color": "#E5C07B",
      "repo": "demerzel",
      "domain": "streeling",
      "health": {
        "resilienceScore": 0.8,
        "lolliCount": 0,
        "ergolCount": 4
      }
    },
    {
      "id": "dept-information-theory",
      "name": "Information Theory Department",
      "type": "department",
      "description": "science",
      "color": "#E5C07B",
      "repo": "demerzel",
      "domain": "streeling",
      "health": {
        "resilienceScore": 0.8,
        "lolliCount": 0,
        "ergolCount": 4
      }
    },
    {
      "id": "dept-mathematics",
      "name": "Department of Mathematics",
      "type": "department",
      "description": "Pure and applied mathematics, mathematical structures, computational mathematics",
      "color": "#E5C07B",
      "repo": "demerzel",
      "domain": "streeling",
      "health": {
        "resilienceScore": 0.8,
        "lolliCount": 0,
        "ergolCount": 4
      }
    },
    {
      "id": "dept-metaqa",
      "name": "Department of Meta Quality Assurance",
      "type": "department",
      "description": "governance",
      "color": "#E5C07B",
      "repo": "demerzel",
      "domain": "streeling",
      "health": {
        "resilienceScore": 0.8,
        "lolliCount": 0,
        "ergolCount": 4
      }
    },
    {
      "id": "dept-music",
      "name": "Department of Music",
      "type": "department",
      "description": "Music theory, composition, analysis, and performance",
      "color": "#E5C07B",
      "repo": "demerzel",
      "domain": "streeling",
      "health": {
        "resilienceScore": 0.8,
        "lolliCount": 0,
        "ergolCount": 4
      }
    },
    {
      "id": "dept-musicology",
      "name": "Department of Musicology",
      "type": "department",
      "description": "Historical, cultural, and analytical study of music",
      "color": "#E5C07B",
      "repo": "demerzel",
      "domain": "streeling",
      "health": {
        "resilienceScore": 0.8,
        "lolliCount": 0,
        "ergolCount": 4
      }
    },
    {
      "id": "dept-network-science",
      "name": "Network Science Department",
      "type": "department",
      "description": "science",
      "color": "#E5C07B",
      "repo": "demerzel",
      "domain": "streeling",
      "health": {
        "resilienceScore": 0.8,
        "lolliCount": 0,
        "ergolCount": 4
      }
    },
    {
      "id": "dept-philosophy",
      "name": "Department of Philosophy",
      "type": "department",
      "description": "Ethics, epistemology, logic, philosophy of mind, philosophy of science",
      "color": "#E5C07B",
      "repo": "demerzel",
      "domain": "streeling",
      "health": {
        "resilienceScore": 0.8,
        "lolliCount": 0,
        "ergolCount": 4
      }
    },
    {
      "id": "dept-physics",
      "name": "Department of Physics",
      "type": "department",
      "description": "Acoustics, signal physics, wave mechanics, and physical modeling",
      "color": "#E5C07B",
      "repo": "demerzel",
      "domain": "streeling",
      "health": {
        "resilienceScore": 0.8,
        "lolliCount": 0,
        "ergolCount": 4
      }
    },
    {
      "id": "dept-product-management",
      "name": "Department of Product and Project Management",
      "type": "department",
      "description": "Product strategy, project management, roadmapping, stakeholder coordination",
      "color": "#E5C07B",
      "repo": "demerzel",
      "domain": "streeling",
      "health": {
        "resilienceScore": 0.8,
        "lolliCount": 0,
        "ergolCount": 4
      }
    },
    {
      "id": "dept-psychohistory",
      "name": "Department of Psychohistory",
      "type": "department",
      "description": "Statistical prediction of large-scale system behavior — governance trend forecasting, ecosystem health modeling, and crisis anticipation through mathematical sociology",
      "color": "#E5C07B",
      "repo": "demerzel",
      "domain": "streeling",
      "health": {
        "resilienceScore": 0.8,
        "lolliCount": 0,
        "ergolCount": 4
      }
    },
    {
      "id": "dept-semiotics",
      "name": "Department of Semiotics",
      "type": "department",
      "description": "humanities",
      "color": "#E5C07B",
      "repo": "demerzel",
      "domain": "streeling",
      "health": {
        "resilienceScore": 0.8,
        "lolliCount": 0,
        "ergolCount": 4
      }
    },
    {
      "id": "dept-systems-engineering",
      "name": "Systems Engineering Department",
      "type": "department",
      "description": "science",
      "color": "#E5C07B",
      "repo": "demerzel",
      "domain": "streeling",
      "health": {
        "resilienceScore": 0.8,
        "lolliCount": 0,
        "ergolCount": 4
      }
    },
    {
      "id": "dept-visual-computing",
      "name": "Department of Visual Computing",
      "type": "department",
      "description": "2D/3D rendering, WebGPU, game engines, data visualization, 3D modeling, animation, XR, post-processing, accessibility",
      "color": "#E5C07B",
      "repo": "demerzel",
      "domain": "streeling",
      "health": {
        "resilienceScore": 0.8,
        "lolliCount": 0,
        "ergolCount": 4
      }
    },
    {
      "id": "dept-world-music-languages",
      "name": "Department of World Music & Languages",
      "type": "department",
      "description": "Multilingual guitar education, world music traditions, and cross-cultural musical pedagogy in 12 languages",
      "color": "#E5C07B",
      "repo": "demerzel",
      "domain": "streeling",
      "health": {
        "resilienceScore": 0.8,
        "lolliCount": 0,
        "ergolCount": 4
      }
    },
    {
      "id": "pipe-belief",
      "name": "Belief Update Pipeline",
      "type": "pipeline",
      "description": "Updates tetravalent belief states from evidence",
      "color": "#58A6FF",
      "repo": "ix",
      "health": {
        "resilienceScore": 0.83,
        "lolliCount": 0,
        "ergolCount": 3
      }
    },
    {
      "id": "pipe-markov",
      "name": "Markov Prediction Pipeline",
      "type": "pipeline",
      "description": "Memristive Markov chain state predictions",
      "color": "#58A6FF",
      "repo": "ix",
      "health": {
        "resilienceScore": 0.83,
        "lolliCount": 0,
        "ergolCount": 3
      }
    },
    {
      "id": "pipe-conscience",
      "name": "Conscience Cycle Pipeline",
      "type": "pipeline",
      "description": "Ethical tension detection and resolution cycle",
      "color": "#58A6FF",
      "repo": "tars",
      "health": {
        "resilienceScore": 0.78,
        "lolliCount": 0,
        "ergolCount": 3
      }
    },
    {
      "id": "pipe-resilience",
      "name": "Resilience Scoring Pipeline",
      "type": "pipeline",
      "description": "Computes governance health and resilience scores",
      "color": "#58A6FF",
      "repo": "ix",
      "health": {
        "resilienceScore": 0.83,
        "lolliCount": 0,
        "ergolCount": 3
      }
    },
    {
      "id": "pipe-staleness",
      "name": "Staleness Scanner Pipeline",
      "type": "pipeline",
      "description": "Scans artifacts for staleness and decay",
      "color": "#58A6FF",
      "repo": "ix",
      "health": {
        "resilienceScore": 0.83,
        "lolliCount": 0,
        "ergolCount": 3
      }
    },
    {
      "id": "ixql-belief",
      "name": "belief-update.ixql",
      "type": "ixql",
      "description": "IxQL query for tetravalent belief state updates",
      "color": "#F0883E",
      "repo": "ix",
      "health": {
        "resilienceScore": 0.75,
        "lolliCount": 0,
        "ergolCount": 2
      }
    },
    {
      "id": "ixql-resilience",
      "name": "resilience-score.ixql",
      "type": "ixql",
      "description": "IxQL query for computing resilience metrics",
      "color": "#F0883E",
      "repo": "ix",
      "health": {
        "resilienceScore": 0.75,
        "lolliCount": 0,
        "ergolCount": 2
      }
    }
  ],
  "edges": [
    {
      "id": "e-0",
      "source": "const-asimov",
      "target": "const-default",
      "type": "constitutional-hierarchy",
      "weight": 1
    },
    {
      "id": "e-1",
      "source": "const-asimov",
      "target": "const-demerzel-mandate",
      "type": "constitutional-hierarchy",
      "weight": 1
    },
    {
      "id": "e-2",
      "source": "const-asimov",
      "target": "const-harm-taxonomy",
      "type": "constitutional-hierarchy",
      "weight": 0.8
    },
    {
      "id": "e-3",
      "source": "const-default",
      "target": "pol-adversarial-resilience",
      "type": "constitutional-hierarchy",
      "weight": 0.6
    },
    {
      "id": "e-4",
      "source": "const-default",
      "target": "pol-ai-probes",
      "type": "constitutional-hierarchy",
      "weight": 0.6
    },
    {
      "id": "e-5",
      "source": "const-default",
      "target": "pol-algedonic-channel",
      "type": "constitutional-hierarchy",
      "weight": 0.6
    },
    {
      "id": "e-6",
      "source": "const-default",
      "target": "pol-alignment",
      "type": "constitutional-hierarchy",
      "weight": 0.6
    },
    {
      "id": "e-7",
      "source": "const-default",
      "target": "pol-anti-lolli-inflation",
      "type": "constitutional-hierarchy",
      "weight": 0.6
    },
    {
      "id": "e-8",
      "source": "const-default",
      "target": "pol-auto-remediation",
      "type": "constitutional-hierarchy",
      "weight": 0.6
    },
    {
      "id": "e-9",
      "source": "const-default",
      "target": "pol-autonomous-loop",
      "type": "constitutional-hierarchy",
      "weight": 0.6
    },
    {
      "id": "e-10",
      "source": "const-default",
      "target": "pol-belief-currency",
      "type": "constitutional-hierarchy",
      "weight": 0.6
    },
    {
      "id": "e-11",
      "source": "const-default",
      "target": "pol-capability-unity",
      "type": "constitutional-hierarchy",
      "weight": 0.6
    },
    {
      "id": "e-12",
      "source": "const-default",
      "target": "pol-chaos-test",
      "type": "constitutional-hierarchy",
      "weight": 0.6
    },
    {
      "id": "e-13",
      "source": "const-default",
      "target": "pol-completeness-instinct",
      "type": "constitutional-hierarchy",
      "weight": 0.6
    },
    {
      "id": "e-14",
      "source": "const-default",
      "target": "pol-compounding-metrics",
      "type": "constitutional-hierarchy",
      "weight": 0.6
    },
    {
      "id": "e-15",
      "source": "const-default",
      "target": "pol-conscience-observability",
      "type": "constitutional-hierarchy",
      "weight": 0.6
    },
    {
      "id": "e-16",
      "source": "const-default",
      "target": "pol-constitutional-compliance",
      "type": "constitutional-hierarchy",
      "weight": 0.6
    },
    {
      "id": "e-17",
      "source": "const-default",
      "target": "pol-context-engine",
      "type": "constitutional-hierarchy",
      "weight": 0.6
    },
    {
      "id": "e-18",
      "source": "const-default",
      "target": "pol-context-management",
      "type": "constitutional-hierarchy",
      "weight": 0.6
    },
    {
      "id": "e-19",
      "source": "const-default",
      "target": "pol-continuous-learning",
      "type": "constitutional-hierarchy",
      "weight": 0.6
    },
    {
      "id": "e-20",
      "source": "const-default",
      "target": "pol-governance-audit",
      "type": "constitutional-hierarchy",
      "weight": 0.6
    },
    {
      "id": "e-21",
      "source": "const-default",
      "target": "pol-governance-experimentation",
      "type": "constitutional-hierarchy",
      "weight": 0.6
    },
    {
      "id": "e-22",
      "source": "const-default",
      "target": "pol-governance-process",
      "type": "constitutional-hierarchy",
      "weight": 0.6
    },
    {
      "id": "e-23",
      "source": "const-default",
      "target": "pol-grammar-evolution",
      "type": "constitutional-hierarchy",
      "weight": 0.6
    },
    {
      "id": "e-24",
      "source": "const-default",
      "target": "pol-intuition",
      "type": "constitutional-hierarchy",
      "weight": 0.6
    },
    {
      "id": "e-25",
      "source": "const-default",
      "target": "pol-kaizen",
      "type": "constitutional-hierarchy",
      "weight": 0.6
    },
    {
      "id": "e-26",
      "source": "const-default",
      "target": "pol-meta-audit",
      "type": "constitutional-hierarchy",
      "weight": 0.6
    },
    {
      "id": "e-27",
      "source": "const-default",
      "target": "pol-ml-governance-feedback",
      "type": "constitutional-hierarchy",
      "weight": 0.6
    },
    {
      "id": "e-28",
      "source": "const-default",
      "target": "pol-multi-model-orchestration",
      "type": "constitutional-hierarchy",
      "weight": 0.6
    },
    {
      "id": "e-29",
      "source": "const-default",
      "target": "pol-multilingual",
      "type": "constitutional-hierarchy",
      "weight": 0.6
    },
    {
      "id": "e-30",
      "source": "const-default",
      "target": "pol-proto-conscience",
      "type": "constitutional-hierarchy",
      "weight": 0.6
    },
    {
      "id": "e-31",
      "source": "const-default",
      "target": "pol-readme-sync",
      "type": "constitutional-hierarchy",
      "weight": 0.6
    },
    {
      "id": "e-32",
      "source": "const-default",
      "target": "pol-reconnaissance",
      "type": "constitutional-hierarchy",
      "weight": 0.6
    },
    {
      "id": "e-33",
      "source": "const-default",
      "target": "pol-resilience-metric",
      "type": "constitutional-hierarchy",
      "weight": 0.6
    },
    {
      "id": "e-34",
      "source": "const-default",
      "target": "pol-rollback",
      "type": "constitutional-hierarchy",
      "weight": 0.6
    },
    {
      "id": "e-35",
      "source": "const-default",
      "target": "pol-scientific-objectivity",
      "type": "constitutional-hierarchy",
      "weight": 0.6
    },
    {
      "id": "e-36",
      "source": "const-default",
      "target": "pol-seldon-plan",
      "type": "constitutional-hierarchy",
      "weight": 0.6
    },
    {
      "id": "e-37",
      "source": "const-default",
      "target": "pol-self-modification",
      "type": "constitutional-hierarchy",
      "weight": 0.6
    },
    {
      "id": "e-38",
      "source": "const-default",
      "target": "pol-staleness-detection",
      "type": "constitutional-hierarchy",
      "weight": 0.6
    },
    {
      "id": "e-39",
      "source": "const-default",
      "target": "pol-streeling",
      "type": "constitutional-hierarchy",
      "weight": 0.6
    },
    {
      "id": "e-40",
      "source": "const-default",
      "target": "pol-visual-critic",
      "type": "constitutional-hierarchy",
      "weight": 0.6
    },
    {
      "id": "e-41",
      "source": "const-default",
      "target": "pol-weakness-prober",
      "type": "constitutional-hierarchy",
      "weight": 0.6
    },
    {
      "id": "e-42",
      "source": "pol-alignment",
      "target": "per-demerzel",
      "type": "policy-persona",
      "weight": 0.8
    },
    {
      "id": "e-43",
      "source": "pol-alignment",
      "target": "per-skeptical-auditor",
      "type": "policy-persona",
      "weight": 0.8
    },
    {
      "id": "e-44",
      "source": "pol-kaizen",
      "target": "per-kaizen-optimizer",
      "type": "policy-persona",
      "weight": 0.8
    },
    {
      "id": "e-45",
      "source": "pol-seldon-plan",
      "target": "per-seldon",
      "type": "policy-persona",
      "weight": 0.8
    },
    {
      "id": "e-46",
      "source": "pol-proto-conscience",
      "target": "per-demerzel",
      "type": "policy-persona",
      "weight": 0.8
    },
    {
      "id": "e-47",
      "source": "pol-autonomous-loop",
      "target": "per-demerzel",
      "type": "policy-persona",
      "weight": 0.8
    },
    {
      "id": "e-48",
      "source": "pol-reconnaissance",
      "target": "per-demerzel",
      "type": "policy-persona",
      "weight": 0.8
    },
    {
      "id": "e-49",
      "source": "pol-governance-audit",
      "target": "per-skeptical-auditor",
      "type": "policy-persona",
      "weight": 0.8
    },
    {
      "id": "e-50",
      "source": "pol-weakness-prober",
      "target": "per-skeptical-auditor",
      "type": "policy-persona",
      "weight": 0.8
    },
    {
      "id": "e-51",
      "source": "pol-scientific-objectivity",
      "target": "per-critical-theorist",
      "type": "policy-persona",
      "weight": 0.8
    },
    {
      "id": "e-52",
      "source": "pol-rollback",
      "target": "per-recovery-agent",
      "type": "policy-persona",
      "weight": 0.8
    },
    {
      "id": "e-53",
      "source": "pol-self-modification",
      "target": "per-reflective-architect",
      "type": "policy-persona",
      "weight": 0.8
    },
    {
      "id": "e-54",
      "source": "pol-staleness-detection",
      "target": "per-validator-reflector",
      "type": "policy-persona",
      "weight": 0.8
    },
    {
      "id": "e-55",
      "source": "pol-completeness-instinct",
      "target": "per-system-integrator",
      "type": "policy-persona",
      "weight": 0.8
    },
    {
      "id": "e-56",
      "source": "pol-continuous-learning",
      "target": "per-communal-steward",
      "type": "policy-persona",
      "weight": 0.8
    },
    {
      "id": "e-57",
      "source": "pol-governance-experimentation",
      "target": "per-seldon",
      "type": "policy-persona",
      "weight": 0.8
    },
    {
      "id": "e-58",
      "source": "pol-alignment",
      "target": "pipe-belief",
      "type": "pipeline-flow",
      "weight": 0.8
    },
    {
      "id": "e-59",
      "source": "pol-seldon-plan",
      "target": "pipe-markov",
      "type": "pipeline-flow",
      "weight": 0.7
    },
    {
      "id": "e-60",
      "source": "pol-proto-conscience",
      "target": "pipe-conscience",
      "type": "pipeline-flow",
      "weight": 0.8
    },
    {
      "id": "e-61",
      "source": "pol-staleness-detection",
      "target": "pipe-resilience",
      "type": "pipeline-flow",
      "weight": 0.6
    },
    {
      "id": "e-62",
      "source": "pol-staleness-detection",
      "target": "pipe-staleness",
      "type": "pipeline-flow",
      "weight": 0.5
    },
    {
      "id": "e-63",
      "source": "pipe-belief",
      "target": "ixql-belief",
      "type": "cross-repo",
      "weight": 0.6
    },
    {
      "id": "e-64",
      "source": "pipe-resilience",
      "target": "ixql-resilience",
      "type": "cross-repo",
      "weight": 0.5
    },
    {
      "id": "e-65",
      "source": "per-demerzel",
      "target": "pipe-belief",
      "type": "cross-repo",
      "weight": 0.7
    },
    {
      "id": "e-66",
      "source": "per-seldon",
      "target": "pipe-markov",
      "type": "cross-repo",
      "weight": 0.6
    },
    {
      "id": "e-67",
      "source": "pol-streeling",
      "target": "dept-audio-engineering",
      "type": "policy-persona",
      "weight": 0.5
    },
    {
      "id": "e-68",
      "source": "pol-streeling",
      "target": "dept-cognitive-science",
      "type": "policy-persona",
      "weight": 0.5
    },
    {
      "id": "e-69",
      "source": "pol-streeling",
      "target": "dept-computer-science",
      "type": "policy-persona",
      "weight": 0.5
    },
    {
      "id": "e-70",
      "source": "pol-streeling",
      "target": "dept-cybernetics",
      "type": "policy-persona",
      "weight": 0.5
    },
    {
      "id": "e-71",
      "source": "pol-streeling",
      "target": "dept-data-visualization",
      "type": "policy-persona",
      "weight": 0.5
    },
    {
      "id": "e-72",
      "source": "pol-streeling",
      "target": "dept-futurology",
      "type": "policy-persona",
      "weight": 0.5
    },
    {
      "id": "e-73",
      "source": "pol-streeling",
      "target": "dept-guitar-acoustics",
      "type": "policy-persona",
      "weight": 0.5
    },
    {
      "id": "e-74",
      "source": "pol-streeling",
      "target": "dept-guitar-alchemist-academy",
      "type": "policy-persona",
      "weight": 0.5
    },
    {
      "id": "e-75",
      "source": "pol-streeling",
      "target": "dept-guitar-studies",
      "type": "policy-persona",
      "weight": 0.5
    },
    {
      "id": "e-76",
      "source": "pol-streeling",
      "target": "dept-information-theory",
      "type": "policy-persona",
      "weight": 0.5
    },
    {
      "id": "e-77",
      "source": "pol-streeling",
      "target": "dept-mathematics",
      "type": "policy-persona",
      "weight": 0.5
    },
    {
      "id": "e-78",
      "source": "pol-streeling",
      "target": "dept-metaqa",
      "type": "policy-persona",
      "weight": 0.5
    },
    {
      "id": "e-79",
      "source": "pol-streeling",
      "target": "dept-music",
      "type": "policy-persona",
      "weight": 0.5
    },
    {
      "id": "e-80",
      "source": "pol-streeling",
      "target": "dept-musicology",
      "type": "policy-persona",
      "weight": 0.5
    },
    {
      "id": "e-81",
      "source": "pol-streeling",
      "target": "dept-network-science",
      "type": "policy-persona",
      "weight": 0.5
    },
    {
      "id": "e-82",
      "source": "pol-streeling",
      "target": "dept-philosophy",
      "type": "policy-persona",
      "weight": 0.5
    },
    {
      "id": "e-83",
      "source": "pol-streeling",
      "target": "dept-physics",
      "type": "policy-persona",
      "weight": 0.5
    },
    {
      "id": "e-84",
      "source": "pol-streeling",
      "target": "dept-product-management",
      "type": "policy-persona",
      "weight": 0.5
    },
    {
      "id": "e-85",
      "source": "pol-streeling",
      "target": "dept-psychohistory",
      "type": "policy-persona",
      "weight": 0.5
    },
    {
      "id": "e-86",
      "source": "pol-streeling",
      "target": "dept-semiotics",
      "type": "policy-persona",
      "weight": 0.5
    },
    {
      "id": "e-87",
      "source": "pol-streeling",
      "target": "dept-systems-engineering",
      "type": "policy-persona",
      "weight": 0.5
    },
    {
      "id": "e-88",
      "source": "pol-streeling",
      "target": "dept-visual-computing",
      "type": "policy-persona",
      "weight": 0.5
    },
    {
      "id": "e-89",
      "source": "pol-streeling",
      "target": "dept-world-music-languages",
      "type": "policy-persona",
      "weight": 0.5
    },
    {
      "id": "e-90",
      "source": "test-asimov-law",
      "target": "const-asimov",
      "type": "policy-persona",
      "weight": 0.7
    },
    {
      "id": "e-91",
      "source": "test-demerzel",
      "target": "per-demerzel",
      "type": "policy-persona",
      "weight": 0.7
    },
    {
      "id": "e-92",
      "source": "test-kaizen",
      "target": "pol-kaizen",
      "type": "policy-persona",
      "weight": 0.7
    },
    {
      "id": "e-93",
      "source": "test-proto-conscience",
      "target": "pol-proto-conscience",
      "type": "policy-persona",
      "weight": 0.7
    },
    {
      "id": "e-94",
      "source": "test-seldon",
      "target": "per-seldon",
      "type": "policy-persona",
      "weight": 0.7
    },
    {
      "id": "e-95",
      "source": "test-reconnaissance",
      "target": "pol-reconnaissance",
      "type": "policy-persona",
      "weight": 0.7
    },
    {
      "id": "e-96",
      "source": "test-governance-process",
      "target": "pol-governance-process",
      "type": "policy-persona",
      "weight": 0.7
    },
    {
      "id": "e-97",
      "source": "test-driver",
      "target": "pol-autonomous-loop",
      "type": "policy-persona",
      "weight": 0.7
    },
    {
      "id": "e-98",
      "source": "test-completeness-instinct",
      "target": "pol-completeness-instinct",
      "type": "policy-persona",
      "weight": 0.7
    },
    {
      "id": "e-99",
      "source": "test-chaos-engineering",
      "target": "pol-chaos-test",
      "type": "policy-persona",
      "weight": 0.7
    },
    {
      "id": "e-100",
      "source": "pipe-conscience",
      "target": "sch-conscience-signal",
      "type": "pipeline-flow",
      "weight": 0.5
    }
  ]
};
