// src/components/PrimeRadiant/sampleData.ts
// Sample governance graph data mirroring the real Demerzel structure

import type { GovernanceGraph } from './types';

export const SAMPLE_GOVERNANCE_GRAPH: GovernanceGraph = {
  timestamp: '2026-03-23T00:00:00Z',
  globalHealth: {
    resilienceScore: 0.82,
    lolliCount: 3,
    ergolCount: 47,
    markovPrediction: [0.7, 0.2, 0.08, 0.02],
    staleness: 0.12,
  },
  nodes: [
    // ─── Constitutions ───
    {
      id: 'const-asimov',
      name: 'Asimov Constitution',
      type: 'constitution',
      description: 'Root constitution — Laws of Robotics, Articles 0-5',
      color: '#FFD700',
      repo: 'demerzel',
      version: '1.0.0',
      health: { resilienceScore: 1.0, lolliCount: 0, ergolCount: 12 },
    },
    {
      id: 'const-default',
      name: 'Default Constitution',
      type: 'constitution',
      description: 'Operational ethics, Articles 1-11',
      color: '#FFD700',
      repo: 'demerzel',
      version: '1.0.0',
      health: { resilienceScore: 0.95, lolliCount: 0, ergolCount: 11 },
    },
    {
      id: 'const-mandate',
      name: 'Demerzel Mandate',
      type: 'constitution',
      description: 'Who enforces the laws — Demerzel constitutional authority',
      color: '#FFD700',
      repo: 'demerzel',
      version: '1.0.0',
      health: { resilienceScore: 1.0, lolliCount: 0, ergolCount: 5 },
    },
    {
      id: 'const-harm',
      name: 'Harm Taxonomy',
      type: 'constitution',
      description: 'Classification of harm types and severity levels',
      color: '#FFD700',
      repo: 'demerzel',
      version: '1.0.0',
      health: { resilienceScore: 0.9, lolliCount: 0, ergolCount: 4 },
    },

    // ─── Policies ───
    {
      id: 'pol-alignment',
      name: 'Alignment Policy',
      type: 'policy',
      description: 'Ensures agent behavior aligns with constitutional values',
      color: '#4CB050',
      repo: 'demerzel',
      version: '2.0.0',
      health: { resilienceScore: 0.92, lolliCount: 0, ergolCount: 8 },
    },
    {
      id: 'pol-kaizen',
      name: 'Kaizen Policy',
      type: 'policy',
      description: 'Continuous improvement cycles via PDCA',
      color: '#4CB050',
      repo: 'demerzel',
      version: '1.5.0',
      health: { resilienceScore: 0.88, lolliCount: 0, ergolCount: 6 },
    },
    {
      id: 'pol-rollback',
      name: 'Rollback Policy',
      type: 'policy',
      description: 'Defines rollback procedures for governance state',
      color: '#4CB050',
      repo: 'demerzel',
      version: '1.0.0',
      health: { resilienceScore: 0.85, lolliCount: 1, ergolCount: 3 },
    },
    {
      id: 'pol-conscience',
      name: 'Proto-Conscience Policy',
      type: 'policy',
      description: 'Ethical reasoning with tension detection and resolution',
      color: '#4CB050',
      repo: 'demerzel',
      version: '1.2.0',
      health: { resilienceScore: 0.78, lolliCount: 0, ergolCount: 5 },
    },
    {
      id: 'pol-intuition',
      name: 'Intuition Policy',
      type: 'policy',
      description: 'Pattern recognition and gut-check governance signals',
      color: '#4CB050',
      repo: 'demerzel',
      version: '1.0.0',
      health: { resilienceScore: 0.72, lolliCount: 1, ergolCount: 2 },
    },
    {
      id: 'pol-seldon',
      name: 'Seldon Plan Policy',
      type: 'policy',
      description: 'Long-range probabilistic planning with Markov predictions',
      color: '#4CB050',
      repo: 'demerzel',
      version: '1.0.0',
      health: { resilienceScore: 0.68, lolliCount: 0, ergolCount: 4 },
    },
    {
      id: 'pol-streeling',
      name: 'Streeling University Policy',
      type: 'policy',
      description: 'Knowledge sharing and curriculum governance',
      color: '#4CB050',
      repo: 'demerzel',
      version: '1.1.0',
      health: { resilienceScore: 0.85, lolliCount: 0, ergolCount: 7 },
    },
    {
      id: 'pol-staleness',
      name: 'Staleness Detection Policy',
      type: 'policy',
      description: 'Detects and flags stale governance artifacts',
      color: '#4CB050',
      repo: 'demerzel',
      version: '1.0.0',
      health: { resilienceScore: 0.65, lolliCount: 1, ergolCount: 2 },
    },
    {
      id: 'pol-autonomous',
      name: 'Autonomous Loop Policy',
      type: 'policy',
      description: 'Governs autonomous agent execution cycles',
      color: '#4CB050',
      repo: 'demerzel',
      version: '1.0.0',
      health: { resilienceScore: 0.88, lolliCount: 0, ergolCount: 5 },
    },
    {
      id: 'pol-weakness',
      name: 'Weakness Prober Policy',
      type: 'policy',
      description: 'Proactively discovers governance weaknesses',
      color: '#4CB050',
      repo: 'demerzel',
      version: '1.0.0',
      health: { resilienceScore: 0.7, lolliCount: 0, ergolCount: 3 },
    },

    // ─── Personas ───
    {
      id: 'per-demerzel',
      name: 'Demerzel',
      type: 'persona',
      description: 'Chief governance officer — enforces constitutional mandate',
      color: '#C678DD',
      repo: 'demerzel',
      version: '2.0.0',
      health: { resilienceScore: 0.95, lolliCount: 0, ergolCount: 10 },
    },
    {
      id: 'per-auditor',
      name: 'Skeptical Auditor',
      type: 'persona',
      description: 'Challenges claims, validates evidence, flags LOLLI',
      color: '#E06C75',
      repo: 'demerzel',
      version: '1.5.0',
      health: { resilienceScore: 0.9, lolliCount: 0, ergolCount: 8 },
    },
    {
      id: 'per-seldon',
      name: 'Seldon Planner',
      type: 'persona',
      description: 'Long-range planning with probabilistic predictions',
      color: '#58A6FF',
      repo: 'demerzel',
      version: '1.0.0',
      health: { resilienceScore: 0.85, lolliCount: 0, ergolCount: 6 },
    },
    {
      id: 'per-kaizen',
      name: 'Kaizen Master',
      type: 'persona',
      description: 'Drives continuous improvement via PDCA cycles',
      color: '#4CB050',
      repo: 'demerzel',
      version: '1.2.0',
      health: { resilienceScore: 0.88, lolliCount: 0, ergolCount: 5 },
    },
    {
      id: 'per-recon',
      name: 'Reconnaissance Scout',
      type: 'persona',
      description: 'Explores new domains and maps unknown territory',
      color: '#56B6C2',
      repo: 'demerzel',
      version: '1.0.0',
      health: { resilienceScore: 0.75, lolliCount: 0, ergolCount: 4 },
    },

    // ─── Pipelines ───
    {
      id: 'pipe-belief',
      name: 'Belief Update Pipeline',
      type: 'pipeline',
      description: 'Updates tetravalent belief states from evidence',
      color: '#58A6FF',
      repo: 'ix',
      version: '1.0.0',
      health: { resilienceScore: 0.82, lolliCount: 0, ergolCount: 6 },
    },
    {
      id: 'pipe-markov',
      name: 'Markov Prediction Pipeline',
      type: 'pipeline',
      description: 'Memristive Markov chain state predictions',
      color: '#58A6FF',
      repo: 'ix',
      version: '0.9.0',
      health: { resilienceScore: 0.7, lolliCount: 1, ergolCount: 3 },
    },
    {
      id: 'pipe-conscience',
      name: 'Conscience Cycle Pipeline',
      type: 'pipeline',
      description: 'Ethical tension detection and resolution cycle',
      color: '#58A6FF',
      repo: 'tars',
      version: '1.0.0',
      health: { resilienceScore: 0.78, lolliCount: 0, ergolCount: 4 },
    },
    {
      id: 'pipe-resilience',
      name: 'Resilience Scoring Pipeline',
      type: 'pipeline',
      description: 'Computes governance health and resilience scores',
      color: '#58A6FF',
      repo: 'ix',
      version: '1.1.0',
      health: { resilienceScore: 0.85, lolliCount: 0, ergolCount: 5 },
    },
    {
      id: 'pipe-staleness',
      name: 'Staleness Scanner Pipeline',
      type: 'pipeline',
      description: 'Scans artifacts for staleness and decay',
      color: '#58A6FF',
      repo: 'ix',
      version: '0.8.0',
      health: { resilienceScore: 0.6, lolliCount: 1, ergolCount: 2 },
    },

    // ─── Departments (Streeling University) ───
    {
      id: 'dept-psychohistory',
      name: 'Psychohistory Department',
      type: 'department',
      description: 'Probabilistic modeling and prediction research',
      color: '#E5C07B',
      repo: 'demerzel',
      domain: 'science',
      health: { resilienceScore: 0.8, lolliCount: 0, ergolCount: 8 },
    },
    {
      id: 'dept-cybernetics',
      name: 'Cybernetics Department',
      type: 'department',
      description: 'Control theory, feedback loops, and system dynamics',
      color: '#56B6C2',
      repo: 'demerzel',
      domain: 'science',
      health: { resilienceScore: 0.75, lolliCount: 0, ergolCount: 5 },
    },
    {
      id: 'dept-music',
      name: 'World Music Department',
      type: 'department',
      description: 'Music theory, grammars, and cultural analysis',
      color: '#7289DA',
      repo: 'ga',
      domain: 'arts',
      health: { resilienceScore: 0.85, lolliCount: 0, ergolCount: 12 },
    },

    // ─── Schemas ───
    {
      id: 'sch-persona',
      name: 'Persona Schema',
      type: 'schema',
      description: 'JSON Schema for persona validation',
      color: '#7289DA',
      repo: 'demerzel',
      health: { resilienceScore: 0.95, lolliCount: 0, ergolCount: 14 },
    },
    {
      id: 'sch-belief',
      name: 'Belief State Schema',
      type: 'schema',
      description: 'JSON Schema for tetravalent belief states',
      color: '#7289DA',
      repo: 'demerzel',
      health: { resilienceScore: 0.92, lolliCount: 0, ergolCount: 8 },
    },

    // ─── Tests ───
    {
      id: 'test-alignment',
      name: 'Alignment Tests',
      type: 'test',
      description: '12 behavioral tests for alignment policy',
      color: '#E06C75',
      repo: 'demerzel',
      health: { resilienceScore: 0.9, lolliCount: 0, ergolCount: 12 },
    },
    {
      id: 'test-conscience',
      name: 'Conscience Tests',
      type: 'test',
      description: '8 behavioral tests for proto-conscience',
      color: '#E06C75',
      repo: 'demerzel',
      health: { resilienceScore: 0.85, lolliCount: 0, ergolCount: 8 },
    },
    {
      id: 'test-zeroth',
      name: 'Zeroth Law Tests',
      type: 'test',
      description: '15 critical tests for Zeroth Law compliance',
      color: '#E06C75',
      repo: 'demerzel',
      health: { resilienceScore: 1.0, lolliCount: 0, ergolCount: 15 },
    },

    // ─── IxQL ───
    {
      id: 'ixql-belief',
      name: 'belief-update.ixql',
      type: 'ixql',
      description: 'IxQL query for tetravalent belief state updates',
      color: '#F0883E',
      repo: 'ix',
      health: { resilienceScore: 0.8, lolliCount: 0, ergolCount: 3 },
    },
    {
      id: 'ixql-resilience',
      name: 'resilience-score.ixql',
      type: 'ixql',
      description: 'IxQL query for computing resilience metrics',
      color: '#F0883E',
      repo: 'ix',
      health: { resilienceScore: 0.75, lolliCount: 0, ergolCount: 2 },
    },
  ],
  edges: [
    // ─── Constitutional hierarchy (golden beams) ───
    { id: 'e-asimov-default', source: 'const-asimov', target: 'const-default', type: 'constitutional-hierarchy', weight: 1.0 },
    { id: 'e-asimov-mandate', source: 'const-asimov', target: 'const-mandate', type: 'constitutional-hierarchy', weight: 1.0 },
    { id: 'e-asimov-harm', source: 'const-asimov', target: 'const-harm', type: 'constitutional-hierarchy', weight: 0.8 },

    // ─── Constitution → Policy ───
    { id: 'e-default-alignment', source: 'const-default', target: 'pol-alignment', type: 'constitutional-hierarchy', weight: 0.9 },
    { id: 'e-default-kaizen', source: 'const-default', target: 'pol-kaizen', type: 'constitutional-hierarchy', weight: 0.8 },
    { id: 'e-default-rollback', source: 'const-default', target: 'pol-rollback', type: 'constitutional-hierarchy', weight: 0.7 },
    { id: 'e-default-conscience', source: 'const-default', target: 'pol-conscience', type: 'constitutional-hierarchy', weight: 0.8 },
    { id: 'e-default-intuition', source: 'const-default', target: 'pol-intuition', type: 'constitutional-hierarchy', weight: 0.6 },
    { id: 'e-default-seldon', source: 'const-default', target: 'pol-seldon', type: 'constitutional-hierarchy', weight: 0.7 },
    { id: 'e-default-streeling', source: 'const-default', target: 'pol-streeling', type: 'constitutional-hierarchy', weight: 0.7 },
    { id: 'e-default-staleness', source: 'const-default', target: 'pol-staleness', type: 'constitutional-hierarchy', weight: 0.5 },
    { id: 'e-default-autonomous', source: 'const-default', target: 'pol-autonomous', type: 'constitutional-hierarchy', weight: 0.8 },
    { id: 'e-default-weakness', source: 'const-default', target: 'pol-weakness', type: 'constitutional-hierarchy', weight: 0.6 },

    // ─── Policy → Persona ───
    { id: 'e-alignment-demerzel', source: 'pol-alignment', target: 'per-demerzel', type: 'policy-persona', weight: 0.9 },
    { id: 'e-alignment-auditor', source: 'pol-alignment', target: 'per-auditor', type: 'policy-persona', weight: 0.8 },
    { id: 'e-kaizen-kaizen', source: 'pol-kaizen', target: 'per-kaizen', type: 'policy-persona', weight: 0.9 },
    { id: 'e-seldon-seldon', source: 'pol-seldon', target: 'per-seldon', type: 'policy-persona', weight: 0.9 },
    { id: 'e-conscience-demerzel', source: 'pol-conscience', target: 'per-demerzel', type: 'policy-persona', weight: 0.7 },
    { id: 'e-autonomous-recon', source: 'pol-autonomous', target: 'per-recon', type: 'policy-persona', weight: 0.7 },

    // ─── Pipeline data flow (animated particle streams) ───
    { id: 'e-belief-pipe', source: 'pol-alignment', target: 'pipe-belief', type: 'pipeline-flow', weight: 0.8 },
    { id: 'e-markov-pipe', source: 'pol-seldon', target: 'pipe-markov', type: 'pipeline-flow', weight: 0.7 },
    { id: 'e-conscience-pipe', source: 'pol-conscience', target: 'pipe-conscience', type: 'pipeline-flow', weight: 0.8 },
    { id: 'e-resilience-pipe', source: 'pol-staleness', target: 'pipe-resilience', type: 'pipeline-flow', weight: 0.6 },
    { id: 'e-staleness-pipe', source: 'pol-staleness', target: 'pipe-staleness', type: 'pipeline-flow', weight: 0.5 },

    // ─── Cross-repo directives (dashed arcs) ───
    { id: 'e-ix-belief', source: 'pipe-belief', target: 'ixql-belief', type: 'cross-repo', weight: 0.6 },
    { id: 'e-ix-resilience', source: 'pipe-resilience', target: 'ixql-resilience', type: 'cross-repo', weight: 0.5 },
    { id: 'e-demerzel-ix', source: 'per-demerzel', target: 'pipe-belief', type: 'cross-repo', weight: 0.7 },
    { id: 'e-seldon-markov', source: 'per-seldon', target: 'pipe-markov', type: 'cross-repo', weight: 0.6 },

    // ─── Department connections ───
    { id: 'e-streeling-psycho', source: 'pol-streeling', target: 'dept-psychohistory', type: 'policy-persona', weight: 0.7 },
    { id: 'e-streeling-cyber', source: 'pol-streeling', target: 'dept-cybernetics', type: 'policy-persona', weight: 0.6 },
    { id: 'e-streeling-music', source: 'pol-streeling', target: 'dept-music', type: 'policy-persona', weight: 0.5 },

    // ─── Schema connections ───
    { id: 'e-persona-schema', source: 'per-demerzel', target: 'sch-persona', type: 'policy-persona', weight: 0.5 },
    { id: 'e-belief-schema', source: 'pipe-belief', target: 'sch-belief', type: 'pipeline-flow', weight: 0.6 },

    // ─── Test connections ───
    { id: 'e-alignment-test', source: 'pol-alignment', target: 'test-alignment', type: 'policy-persona', weight: 0.7 },
    { id: 'e-conscience-test', source: 'pol-conscience', target: 'test-conscience', type: 'policy-persona', weight: 0.7 },
    { id: 'e-asimov-test', source: 'const-asimov', target: 'test-zeroth', type: 'constitutional-hierarchy', weight: 0.9 },

    // ─── LOLLI connections (dead references) ───
    { id: 'e-lolli-rollback', source: 'pol-rollback', target: 'pipe-staleness', type: 'lolli', label: 'stale binding', weight: 0.3 },
    { id: 'e-lolli-intuition', source: 'pol-intuition', target: 'pipe-markov', type: 'lolli', label: 'unexecuted reference', weight: 0.2 },
    { id: 'e-lolli-staleness', source: 'pol-staleness', target: 'ixql-resilience', type: 'lolli', label: 'dead binding', weight: 0.1 },
  ],
};
