namespace GA.Business.DSL.SourceGen;

using System.Text;

/// <summary>
/// Emits F# source from a list of <see cref="EbnfRule"/> nodes.
/// Produces two artefacts per grammar:
///   1. A discriminated union representing the AST node types (domain level).
///   2. FParsec parser combinators that parse text into those types (grammar level).
/// </summary>
public sealed class FSharpEmitter
{
    private readonly string _grammarName;
    private readonly string _moduleName;

    public FSharpEmitter(string grammarName)
    {
        _grammarName = grammarName;
        _moduleName  = ToPascalCase(grammarName);
    }

    public string Emit(IReadOnlyList<EbnfRule> rules)
    {
        var sb = new StringBuilder();

        sb.AppendLine($"// Auto-generated from {_grammarName}.ebnf — do not edit manually.");
        sb.AppendLine($"// Generated by GA.Business.DSL.SourceGen EbnfGeneratorTask.");
        sb.AppendLine();
        sb.AppendLine($"module GA.Business.Core.Generated.{_moduleName}Grammar");
        sb.AppendLine();
        sb.AppendLine("open FParsec");
        sb.AppendLine();

        // ── Part 1: AST discriminated unions ──────────────────────────────────
        sb.AppendLine($"// ── {_grammarName} AST types ──");
        sb.AppendLine();
        foreach (var rule in rules)
        {
            var typeName = ToPascalCase(rule.Name);
            sb.AppendLine($"/// AST node for '{rule.Name}' rule.");
            sb.AppendLine($"type {typeName}Node =");
            EmitDuCases(sb, rule, rules, "    ");
            sb.AppendLine();
        }

        // ── Part 2: FParsec parser combinators ────────────────────────────────
        sb.AppendLine($"// ── {_grammarName} FParsec parsers ──");
        sb.AppendLine();

        // Forward references for recursive rules
        foreach (var rule in rules)
        {
            var typeName = ToPascalCase(rule.Name);
            var refVar   = ToCamelCase(rule.Name) + "Ref";
            sb.AppendLine($"let private {refVar}, private {refVar}Impl = createParserForwardedToRef<{typeName}Node, unit> ()");
        }
        sb.AppendLine();

        // Actual parser implementations
        foreach (var rule in rules)
        {
            var typeName = ToPascalCase(rule.Name);
            var parserName = ToCamelCase(rule.Name) + "Parser";
            sb.AppendLine($"let private {parserName} : Parser<{typeName}Node, unit> =");
            sb.Append("    ");
            EmitParser(sb, rule.Body, ToPascalCase(rule.Name), rules, "    ");
            sb.AppendLine();
            sb.AppendLine();

            var refImpl = ToCamelCase(rule.Name) + "RefImpl";
            sb.AppendLine($"do {refImpl}.Value <- {parserName}");
            sb.AppendLine();
        }

        // Public parse entry point for each top-level rule
        if (rules.Count > 0)
        {
            var first = rules[0];
            var typeName = ToPascalCase(first.Name);
            var parserName = ToCamelCase(first.Name) + "Parser";
            sb.AppendLine($"/// Parse a {_grammarName} from a string. Returns Ok or Error.");
            sb.AppendLine($"let parse (input: string) : Result<{typeName}Node, string> =");
            sb.AppendLine($"    match run ({parserName} .>> eof) input with");
            sb.AppendLine($"    | Success (v, _, _) -> Ok v");
            sb.AppendLine($"    | Failure (msg, _, _) -> Error msg");
        }

        return sb.ToString();
    }

    // ── DU case emission ─────────────────────────────────────────────────────

    private void EmitDuCases(StringBuilder sb, EbnfRule rule, IReadOnlyList<EbnfRule> allRules, string indent)
    {
        switch (rule.Body)
        {
            case EbnfAlt alt:
                foreach (var choice in alt.Alternatives)
                    EmitDuCase(sb, rule.Name, choice, allRules, indent);
                break;
            default:
                // Single-constructor DU
                sb.AppendLine($"{indent}| {ToPascalCase(rule.Name)} of string");
                break;
        }
    }

    private void EmitDuCase(StringBuilder sb, string ruleName, EbnfExpr expr, IReadOnlyList<EbnfRule> allRules, string indent)
    {
        var caseName = ExprToCaseName(ruleName, expr);
        var payload  = ExprToPayload(expr);
        sb.AppendLine($"{indent}| {caseName}{payload}");
    }

    private static string ExprToCaseName(string ruleName, EbnfExpr expr) => expr switch
    {
        EbnfLiteral lit => "Literal_" + SanitizeLiteral(lit.Value),
        EbnfRef r       => ToPascalCase(r.Name),
        _               => ToPascalCase(ruleName) + "Case"
    };

    private static string ExprToPayload(EbnfExpr expr) => expr switch
    {
        EbnfLiteral => "",
        EbnfRef r   => $" of {ToPascalCase(r.Name)}Node",
        _           => " of string"
    };

    // ── Parser emission ──────────────────────────────────────────────────────

    private void EmitParser(StringBuilder sb, EbnfExpr expr, string wrapType, IReadOnlyList<EbnfRule> allRules, string indent)
    {
        switch (expr)
        {
            case EbnfLiteral lit:
                sb.Append($"pstring \"{EscapeFSharp(lit.Value)}\" >>% {wrapType}Case");
                break;

            case EbnfRef r:
                sb.Append(ToCamelCase(r.Name) + "Ref");
                break;

            case EbnfAlt alt:
                sb.AppendLine("choice [");
                for (var i = 0; i < alt.Alternatives.Count; i++)
                {
                    sb.Append($"{indent}    attempt (");
                    EmitParser(sb, alt.Alternatives[i], wrapType, allRules, indent + "    ");
                    sb.Append(")");
                    if (i < alt.Alternatives.Count - 1) sb.AppendLine();
                }
                sb.Append($"{indent}]");
                break;

            case EbnfSeq seq:
                if (seq.Items.Count == 1)
                {
                    EmitParser(sb, seq.Items[0], wrapType, allRules, indent);
                }
                else
                {
                    sb.AppendLine("pipe2");
                    sb.Append($"{indent}    (");
                    EmitParser(sb, seq.Items[0], wrapType, allRules, indent + "    ");
                    sb.AppendLine(")");
                    sb.Append($"{indent}    (");
                    if (seq.Items.Count == 2)
                    {
                        EmitParser(sb, seq.Items[1], wrapType, allRules, indent + "    ");
                        sb.Append(")");
                        sb.Append($"{indent}    (fun a b -> {wrapType}Case)");
                    }
                    else
                    {
                        sb.Append($"// sequence of {seq.Items.Count} items");
                        sb.Append($") (fun a b -> {wrapType}Case)");
                    }
                }
                break;

            case EbnfOptional opt:
                sb.Append("(opt (");
                EmitParser(sb, opt.Inner, wrapType, allRules, indent);
                sb.Append($") |>> Option.toList |>> List.tryHead |>> (Option.defaultValue ({wrapType}Case)))");
                break;

            case EbnfRepeat rep:
                sb.Append("(many (");
                EmitParser(sb, rep.Inner, wrapType, allRules, indent);
                sb.Append($") |>> (fun _ -> {wrapType}Case))");
                break;

            default:
                sb.Append($"preturn {wrapType}Case");
                break;
        }
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private static string ToPascalCase(string s)
    {
        if (string.IsNullOrEmpty(s)) return s;
        var parts = s.Split(['_', ' ', '-'], StringSplitOptions.RemoveEmptyEntries);
        return string.Concat(parts.Select(p => char.ToUpper(p[0]) + p[1..]));
    }

    private static string ToCamelCase(string s)
    {
        var pascal = ToPascalCase(s);
        return char.ToLower(pascal[0]) + pascal[1..];
    }

    private static string SanitizeLiteral(string s)
    {
        // Produce a valid F# identifier fragment from a literal value
        return new string(s.Where(char.IsLetterOrDigit).ToArray());
    }

    private static string EscapeFSharp(string s) =>
        s.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
