namespace GA.Business.DSL.SourceGen;

using System.Text;

/// <summary>
/// Emits F# source from a list of <see cref="EbnfRule"/> nodes.
/// Produces two artefacts per grammar:
///   1. Discriminated union types representing the AST (domain level).
///   2. FParsec parser combinators that parse text into those types (grammar level).
///
/// Design decisions:
///   - Alt rules become multi-case DUs with one case per alternative.
///   - Seq rules become single-case DUs carrying the sequence items as a tuple/fields.
///   - Repeat ({...}) maps to 'T list.
///   - Optional ([...]) maps to 'T option.
///   - Literal-only alt cases use sanitized literal names; ref cases use the referenced type name.
///   - All forward references use createParserForwardedToRef (handles mutual recursion).
///   - Parser alternations always wrap in 'attempt' to handle shared prefixes safely.
///   - Duplicate DU case names are disambiguated with numeric suffixes.
/// </summary>
public sealed class FSharpEmitter(string grammarName)
{
    private readonly string _moduleName = ToPascalCase(grammarName);

    // Set of rule names for ref-resolution
    private HashSet<string> _ruleNames = [];

    public string Emit(IReadOnlyList<EbnfRule> rules)
    {
        _ruleNames = [..rules.Select(r => r.Name)];
        var sb = new StringBuilder();

        sb.AppendLine($"// Auto-generated from {grammarName}.ebnf — do not edit manually.");
        sb.AppendLine($"// Generated by GA.Business.DSL.SourceGen EbnfGeneratorTask.");
        sb.AppendLine();
        sb.AppendLine($"module GA.Business.Core.Generated.{_moduleName}Grammar");
        sb.AppendLine();
        sb.AppendLine("open FParsec");
        sb.AppendLine();

        // ── Part 1: AST types ───────────────────────────────────────────────────
        sb.AppendLine($"// ── {grammarName} AST types ──");
        sb.AppendLine();

        // Use 'and' for mutually recursive types (all types after the first)
        for (var i = 0; i < rules.Count; i++)
        {
            var rule = rules[i];
            var typeName = TypeName(rule.Name);
            var keyword = i == 0 ? "type" : "and";
            sb.AppendLine($"/// AST node for '{rule.Name}' rule.");
            sb.AppendLine($"{keyword} {typeName} =");
            EmitDuCases(sb, rule);
            sb.AppendLine();
        }

        // ── Part 2: FParsec parsers ─────────────────────────────────────────────
        sb.AppendLine($"// ── {grammarName} FParsec parsers ──");
        sb.AppendLine();

        // Forward references for all rules (safe for recursive grammars)
        foreach (var rule in rules)
        {
            var tn = TypeName(rule.Name);
            var rv = RefVar(rule.Name);
            sb.AppendLine($"let private {rv}, private {rv}Impl = createParserForwardedToRef<{tn}, unit> ()");
        }
        sb.AppendLine();

        // Parser implementations
        foreach (var rule in rules)
        {
            var tn = TypeName(rule.Name);
            var pn = ParserName(rule.Name);
            sb.AppendLine($"let private {pn} : Parser<{tn}, unit> =");
            EmitParserForRule(sb, rule, "    ");
            sb.AppendLine();
            sb.AppendLine($"do {RefVar(rule.Name)}Impl.Value <- {pn}");
            sb.AppendLine();
        }

        // Public parse entry point (first rule is the start symbol)
        if (rules.Count > 0)
        {
            var first = rules[0];
            var tn = TypeName(first.Name);
            var pn = ParserName(first.Name);
            sb.AppendLine($"/// Parse {grammarName} from a string. Returns Ok or Error.");
            sb.AppendLine($"let parse (input: string) : Result<{tn}, string> =");
            sb.AppendLine($"    match run ({pn} .>> eof) input with");
            sb.AppendLine($"    | Success (v, _, _) -> Result.Ok v");
            sb.AppendLine($"    | Failure (msg, _, _) -> Result.Error msg");
        }

        return sb.ToString();
    }

    // ═══════════════════════════════════════════════════════════════════════════
    // DU EMISSION
    // ═══════════════════════════════════════════════════════════════════════════

    private void EmitDuCases(StringBuilder sb, EbnfRule rule)
    {
        switch (rule.Body)
        {
            case EbnfAlt alt:
                // Multi-case DU: one case per alternative, with deduplication
                var caseNames = DeduplicateCaseNames(rule.Name, alt.Alternatives);
                for (var i = 0; i < alt.Alternatives.Count; i++)
                {
                    var choice = alt.Alternatives[i];
                    var payload = AltCasePayload(choice);
                    sb.AppendLine($"    | {caseNames[i]}{payload}");
                }
                break;

            case EbnfSeq seq:
                // Single-case DU carrying sequence items
                var seqCaseName = ToPascalCase(rule.Name);
                var fields = SeqPayloadFields(seq);
                sb.AppendLine($"    | {seqCaseName} of {fields}");
                break;

            default:
                // Single-item rule (literal or ref)
                var singlePayload = SinglePayload(rule.Body);
                sb.AppendLine($"    | {ToPascalCase(rule.Name)} of {singlePayload}");
                break;
        }
    }

    /// <summary>
    /// Generate deduplicated DU case names for an alternation.
    /// When two alternatives would produce the same case name, append a numeric suffix.
    /// </summary>
    private static List<string> DeduplicateCaseNames(string ruleName, List<EbnfExpr> alternatives)
    {
        var rawNames = alternatives.Select(choice => RawAltCaseName(ruleName, choice)).ToList();
        var counts = new Dictionary<string, int>();
        var result = new List<string>();

        // First pass: count occurrences
        foreach (var name in rawNames)
            counts[name] = counts.GetValueOrDefault(name) + 1;

        // Second pass: assign names, appending index for duplicates
        var seen = new Dictionary<string, int>();
        foreach (var name in rawNames)
        {
            if (counts[name] > 1)
            {
                var idx = seen.GetValueOrDefault(name) + 1;
                seen[name] = idx;
                result.Add($"{name}{idx}");
            }
            else
            {
                result.Add(name);
            }
        }

        return result;
    }

    /// <summary>Compute payload type string for sequence items.</summary>
    private string SeqPayloadFields(EbnfSeq seq)
    {
        var parts = seq.Items.Select(ItemTypeString).ToList();
        return string.Join(" * ", parts);
    }

    /// <summary>Get the F# type string for an EBNF expression appearing as a field.</summary>
    private string ItemTypeString(EbnfExpr expr) => expr switch
    {
        EbnfRef r when _ruleNames.Contains(r.Name) => TypeName(r.Name),
        EbnfRef => "string", // unresolved ref → string fallback
        EbnfLiteral => "string",
        EbnfOptional opt => $"{ItemTypeString(opt.Inner)} option",
        EbnfRepeat rep => $"{ItemTypeString(rep.Inner)} list",
        EbnfSeq inner => $"({string.Join(" * ", inner.Items.Select(ItemTypeString))})",
        EbnfAlt => "string", // nested anonymous alt → string
        _ => "string"
    };

    private string SinglePayload(EbnfExpr expr) => ItemTypeString(expr);

    /// <summary>Raw name for a DU case (before deduplication).</summary>
    private static string RawAltCaseName(string ruleName, EbnfExpr expr) => expr switch
    {
        EbnfLiteral lit => SanitizeToCaseName(lit.Value),
        EbnfRef r => ToPascalCase(r.Name),
        EbnfSeq => ToPascalCase(ruleName) + "Seq",
        EbnfOptional => ToPascalCase(ruleName) + "Opt",
        EbnfRepeat => ToPascalCase(ruleName) + "List",
        _ => ToPascalCase(ruleName) + "Case"
    };

    /// <summary>Payload for a DU case within an alternation.</summary>
    private string AltCasePayload(EbnfExpr expr) => expr switch
    {
        EbnfLiteral => "", // Literal cases carry no data (they ARE the data)
        EbnfRef r when _ruleNames.Contains(r.Name) => $" of {TypeName(r.Name)}",
        EbnfRef => " of string",
        EbnfSeq seq => $" of {SeqPayloadFields(seq)}",
        _ => ""
    };

    // ═══════════════════════════════════════════════════════════════════════════
    // PARSER EMISSION
    // ═══════════════════════════════════════════════════════════════════════════

    private void EmitParserForRule(StringBuilder sb, EbnfRule rule, string indent)
    {
        var typeName = TypeName(rule.Name);
        var qualifiedCase = $"{typeName}.{ToPascalCase(rule.Name)}";
        switch (rule.Body)
        {
            case EbnfAlt alt:
                EmitAltParser(sb, alt, rule.Name, indent);
                break;

            case EbnfSeq seq:
                EmitSeqParser(sb, seq, qualifiedCase, indent);
                break;

            default:
                // Single-item rule: wrap the parser result in the DU case constructor
                sb.Append(indent);
                EmitAtomParser(sb, rule.Body, null, indent);
                sb.AppendLine($" |>> {qualifiedCase}");
                break;
        }
    }

    /// <summary>Emit a choice parser for an alternation rule.</summary>
    private void EmitAltParser(StringBuilder sb, EbnfAlt alt, string ruleName, string indent)
    {
        var parentType = TypeName(ruleName);
        var caseNames = DeduplicateCaseNames(ruleName, alt.Alternatives);
        sb.AppendLine($"{indent}choice [");
        for (var i = 0; i < alt.Alternatives.Count; i++)
        {
            var choice = alt.Alternatives[i];
            // Qualify case name with parent type to avoid ambiguity with same-named cases in other DUs
            var qualifiedCase = $"{parentType}.{caseNames[i]}";
            sb.Append($"{indent}    attempt (");
            EmitAltBranchParser(sb, choice, qualifiedCase, indent + "    ");
            sb.Append(")");
            if (i < alt.Alternatives.Count - 1) sb.AppendLine();
        }
        sb.AppendLine($" ]");
    }

    /// <summary>Emit parser for one branch of an alternation, wrapping in the DU case.</summary>
    private void EmitAltBranchParser(StringBuilder sb, EbnfExpr expr, string caseName, string indent)
    {
        switch (expr)
        {
            case EbnfLiteral lit:
                sb.Append($"pstring \"{Esc(lit.Value)}\" >>% {caseName}");
                break;

            case EbnfRef r when _ruleNames.Contains(r.Name):
                sb.Append($"{RefVar(r.Name)} |>> {caseName}");
                break;

            case EbnfRef r:
                sb.Append($"pstring \"{Esc(r.Name)}\" >>% {caseName}");
                break;

            case EbnfSeq seq:
                // Sequence inside alt: use pipe2/pipe3 wrapping in the case
                EmitSeqParser(sb, seq, caseName, indent);
                break;

            default:
                sb.Append($"preturn {caseName}");
                break;
        }
    }

    /// <summary>Emit a pipeN parser for a sequence, wrapping results in a DU case.</summary>
    private void EmitSeqParser(StringBuilder sb, EbnfSeq seq, string caseName, string indent)
    {
        var items = seq.Items;

        if (items.Count == 1)
        {
            sb.Append(indent);
            EmitAtomParser(sb, items[0], null, indent);
            sb.Append($" |>> {caseName}");
            return;
        }

        // For 2-5 items, use pipe2-pipe5; for 6+, split into chunks
        EmitPipeN(sb, items, caseName, indent);
    }

    /// <summary>Emit pipe2-pipe5 for sequences, recursively splitting for 6+ items.</summary>
    private void EmitPipeN(StringBuilder sb, List<EbnfExpr> items, string caseName, string indent)
    {
        var count = items.Count;
        var paramNames = Enumerable.Range(0, count).Select(i => $"v{i}").ToList();
        var pipeName = count switch
        {
            2 => "pipe2",
            3 => "pipe3",
            4 => "pipe4",
            5 => "pipe5",
            _ => null
        };

        if (pipeName != null)
        {
            sb.AppendLine($"{indent}{pipeName}");
            foreach (var item in items)
            {
                sb.Append($"{indent}    (");
                EmitAtomParser(sb, item, null, indent + "    ");
                sb.AppendLine(")");
            }
            var args = string.Join(" ", paramNames);
            var tupleArgs = string.Join(", ", paramNames);
            sb.Append($"{indent}    (fun {args} -> {caseName} ({tupleArgs}))");
        }
        else
        {
            // 6+ items: use pipe2 with first item and a pipe for the rest,
            // then flatten in the constructor
            sb.AppendLine($"{indent}pipe2");
            sb.Append($"{indent}    (");
            EmitAtomParser(sb, items[0], null, indent + "    ");
            sb.AppendLine(")");
            sb.AppendLine($"{indent}    (");
            // Recursively emit the rest as a tuple-producing pipe
            var restItems = items.Skip(1).ToList();
            EmitPipeNTuple(sb, restItems, indent + "    ");
            sb.AppendLine($"{indent}    )");
            // Flatten: first item + destructured rest tuple
            var restParams = Enumerable.Range(1, restItems.Count).Select(i => $"v{i}").ToList();
            var allParams = new List<string> { "v0" };
            allParams.AddRange(restParams);
            var destructure = string.Join(", ", restParams);
            var allArgs = string.Join(", ", allParams);
            sb.Append($"{indent}    (fun v0 ({destructure}) -> {caseName} ({allArgs}))");
        }
    }

    /// <summary>Emit a pipeN that produces a raw tuple (no DU wrapping), for use in nested pipe calls.</summary>
    private void EmitPipeNTuple(StringBuilder sb, List<EbnfExpr> items, string indent)
    {
        var count = items.Count;
        var paramNames = Enumerable.Range(0, count).Select(i => $"t{i}").ToList();

        if (count <= 5)
        {
            var pipeName = count switch { 2 => "pipe2", 3 => "pipe3", 4 => "pipe4", _ => "pipe5" };
            sb.AppendLine($"{indent}{pipeName}");
            foreach (var item in items)
            {
                sb.Append($"{indent}    (");
                EmitAtomParser(sb, item, null, indent + "    ");
                sb.AppendLine(")");
            }
            var args = string.Join(" ", paramNames);
            var tupleArgs = string.Join(", ", paramNames);
            sb.Append($"{indent}    (fun {args} -> ({tupleArgs}))");
        }
        else
        {
            // Recursively split
            sb.AppendLine($"{indent}pipe2");
            sb.Append($"{indent}    (");
            EmitAtomParser(sb, items[0], null, indent + "    ");
            sb.AppendLine(")");
            sb.AppendLine($"{indent}    (");
            var restItems = items.Skip(1).ToList();
            EmitPipeNTuple(sb, restItems, indent + "    ");
            sb.AppendLine($"{indent}    )");
            var restParams = Enumerable.Range(1, restItems.Count).Select(i => $"t{i}").ToList();
            var destructure = string.Join(", ", restParams);
            sb.Append($"{indent}    (fun t0 ({destructure}) -> (t0, {destructure}))");
        }
    }

    /// <summary>Emit a parser for a single atom (ref, literal, optional, repeat).</summary>
    private void EmitAtomParser(StringBuilder sb, EbnfExpr expr, string? wrapCase, string indent)
    {
        switch (expr)
        {
            case EbnfRef r when _ruleNames.Contains(r.Name):
                sb.Append(RefVar(r.Name));
                break;

            case EbnfRef r:
                sb.Append($"pstring \"{Esc(r.Name)}\"");
                break;

            case EbnfLiteral lit:
                sb.Append($"pstring \"{Esc(lit.Value)}\"");
                break;

            case EbnfOptional opt:
                sb.Append("opt (");
                EmitAtomParser(sb, opt.Inner, null, indent);
                sb.Append(")");
                break;

            case EbnfRepeat rep:
                sb.Append("many (");
                EmitAtomParser(sb, rep.Inner, null, indent);
                sb.Append(")");
                break;

            case EbnfAlt alt:
                // Inline alternation (e.g., inside a sequence)
                // If alternatives have heterogeneous types, normalize all to string
                var needsStringNormalization = HasHeterogeneousTypes(alt.Alternatives);
                sb.Append("choice [ ");
                for (var i = 0; i < alt.Alternatives.Count; i++)
                {
                    sb.Append("attempt (");
                    EmitAtomParser(sb, alt.Alternatives[i], null, indent);
                    if (needsStringNormalization)
                        sb.Append(" |>> (fun _ -> \"\")");
                    sb.Append(")");
                    if (i < alt.Alternatives.Count - 1) sb.Append("; ");
                }
                sb.Append(" ]");
                break;

            case EbnfSeq seq:
                // Inline sequence — produce a flat tuple
                if (seq.Items.Count == 1)
                {
                    EmitAtomParser(sb, seq.Items[0], null, indent);
                }
                else
                {
                    // Use pipeN to produce flat tuples (avoiding nested tuple issue from .>>.)
                    sb.Append("(");
                    EmitPipeNTuple(sb, seq.Items, indent);
                    sb.Append(")");
                }
                break;

            default:
                sb.Append("preturn ()");
                break;
        }

        if (wrapCase != null) sb.Append($" |>> {wrapCase}");
    }

    // ═══════════════════════════════════════════════════════════════════════════
    // HELPERS
    // ═══════════════════════════════════════════════════════════════════════════

    private static string TypeName(string ruleName) => ToPascalCase(ruleName) + "Node";
    private static string RefVar(string ruleName) => ToCamelCase(ruleName) + "Ref";
    private static string ParserName(string ruleName) => ToCamelCase(ruleName) + "Parser";

    private static string ToPascalCase(string s)
    {
        if (string.IsNullOrEmpty(s)) return s;
        var parts = s.Split(['_', ' ', '-'], StringSplitOptions.RemoveEmptyEntries);
        return string.Concat(parts.Select(p => char.ToUpper(p[0]) + p[1..]));
    }

    private static string ToCamelCase(string s)
    {
        var pascal = ToPascalCase(s);
        return char.ToLower(pascal[0]) + pascal[1..];
    }

    /// <summary>
    /// Produce a valid F# DU case name from a literal string.
    /// Maps symbols to readable names; digits get a prefix.
    /// </summary>
    private static string SanitizeToCaseName(string s)
    {
        if (string.IsNullOrEmpty(s)) return "Empty";

        var sb = new StringBuilder();
        foreach (var ch in s)
        {
            if (char.IsLetterOrDigit(ch))
                sb.Append(ch);
            else
            {
                var name = ch switch
                {
                    '#' => "Sharp",
                    'b' when s == "b" => "Flat", // standalone 'b' in accidental context
                    '♯' => "Sharp",
                    '♭' => "Flat",
                    '♮' => "Natural",
                    '°' => "Dim",
                    'ø' => "HalfDim",
                    'Δ' => "Delta",
                    '+' => "Plus",
                    '-' => "Dash",
                    '/' => "Slash",
                    '.' => "Dot",
                    ':' => "Colon",
                    '!' => "Bang",
                    '@' => "At",
                    '$' => "Dollar",
                    '%' => "Percent",
                    '^' => "Caret",
                    '&' => "Amp",
                    '*' => "Star",
                    '(' => "LParen",
                    ')' => "RParen",
                    '_' => "Under",
                    '=' => "Eq",
                    '~' => "Tilde",
                    '<' => "Lt",
                    '>' => "Gt",
                    '⊗' => "Tensor",
                    '⊕' => "DirectSum",
                    '×' => "Cross",
                    '∘' => "Compose",
                    '∩' => "Intersect",
                    '∪' => "Union",
                    '→' => "Arrow",
                    ' ' => "",
                    _ => $"U{(int)ch:X4}"
                };
                sb.Append(name);
            }
        }

        var result = sb.ToString();
        // Ensure it starts with an uppercase letter (valid F# identifier)
        if (result.Length == 0) return "Empty";
        if (char.IsDigit(result[0])) result = "N" + result;
        result = char.ToUpper(result[0]) + result[1..];
        return result;
    }

    /// <summary>Check if alternatives produce different parser result types.</summary>
    private bool HasHeterogeneousTypes(List<EbnfExpr> alternatives)
    {
        var types = alternatives.Select(ParserResultType).Distinct().ToList();
        return types.Count > 1;
    }

    /// <summary>Get the parser result type string for an expression.</summary>
    private string ParserResultType(EbnfExpr expr) => expr switch
    {
        EbnfRef r when _ruleNames.Contains(r.Name) => TypeName(r.Name),
        EbnfRef => "string",
        EbnfLiteral => "string",
        EbnfOptional opt => $"{ParserResultType(opt.Inner)} option",
        EbnfRepeat rep => $"{ParserResultType(rep.Inner)} list",
        _ => "string"
    };

    private static string Esc(string s) =>
        s.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
